//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:26 PM EDT 
//


package com.tracelink.prodsec.lib.veracode.xml.api.data.buildlist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="build" type="{https://analysiscenter.veracode.com/schema/2.0/buildlist}BuildType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="buildlist_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="account_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="app_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="sandbox_id" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="app_name" use="required" type="{https://analysiscenter.veracode.com/schema/2.0/buildlist}LongRequiredTextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"build"})
@XmlRootElement(name = "buildlist", namespace = "https://analysiscenter.veracode.com/schema/2.0/buildlist")
public class Buildlist {

	@XmlElement(namespace = "https://analysiscenter.veracode.com/schema/2.0/buildlist")
	private List<BuildType> build;
	@XmlAttribute(name = "buildlist_version", required = true)
	private String buildlistVersion;
	@XmlAttribute(name = "account_id", required = true)
	private long accountId;
	@XmlAttribute(name = "app_id", required = true)
	private long appId;
	@XmlAttribute(name = "sandbox_id")
	private Long sandboxId;
	@XmlAttribute(name = "app_name", required = true)
	private String appName;

	/**
	 * Gets the value of the build property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the build property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getBuild().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BuildType }
	 *
	 * @return value of the build property, or an empty list if the build property is null
	 */
	public List<BuildType> getBuild() {
		if (build == null) {
			build = new ArrayList<>();
		}
		return this.build;
	}

	/**
	 * Gets the value of the buildlistVersion property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getBuildlistVersion() {
		return buildlistVersion;
	}

	/**
	 * Sets the value of the buildlistVersion property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setBuildlistVersion(String value) {
		this.buildlistVersion = value;
	}

	/**
	 * Gets the value of the accountId property.
	 *
	 * @return value of the accountId property
	 */
	public long getAccountId() {
		return accountId;
	}

	/**
	 * Sets the value of the accountId property.
	 *
	 * @param value value to set for the accountId property
	 */
	public void setAccountId(long value) {
		this.accountId = value;
	}

	/**
	 * Gets the value of the appId property.
	 *
	 * @return value of the appId property
	 */
	public long getAppId() {
		return appId;
	}

	/**
	 * Sets the value of the appId property.
	 *
	 * @param value value to set for the appId property
	 */
	public void setAppId(long value) {
		this.appId = value;
	}

	/**
	 * Gets the value of the sandboxId property.
	 *
	 * @return possible object is
	 * {@link Long }
	 */
	public Long getSandboxId() {
		return sandboxId;
	}

	/**
	 * Sets the value of the sandboxId property.
	 *
	 * @param value allowed object is
	 *              {@link Long }
	 */
	public void setSandboxId(Long value) {
		this.sandboxId = value;
	}

	/**
	 * Gets the value of the appName property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * Sets the value of the appName property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAppName(String value) {
		this.appName = value;
	}

}
