version: '3.8'

services:
  db:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
    - "db-data:/var/lib/postgres"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    restart: always
    depends_on:
    - db
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/${DB_NAME}
      JDBC_USERNAME: ${DB_USER}
      JDBC_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: prdtest
      SERVER_PORT: 8081

volumes:
  db-data:
