//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.sast.api.data.detailedreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This represents a text paragraph.  There is one attribute:
 * * text:  The text of the paragraph.
 * <p>
 * There may be "bullet item" child elements, indicating list items.
 *
 *
 * <p>Java class for ParaType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ParaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bulletitem" type="{https://www.veracode.com/schema/reports/export/1.0}BulletItemType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParaType", namespace = "https://www.veracode.com/schema/reports/export/1.0", propOrder = {
		"bulletitem"
})
public class ParaType {

	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
	protected List<BulletItemType> bulletitem;
	@XmlAttribute(name = "text", required = true)
	protected String text;

	/**
	 * Gets the value of the bulletitem property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the bulletitem property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getBulletitem().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BulletItemType }
	 *
	 * @return value of the bulletitem property, or an empty list if the bulletitem property is null
	 */
	public List<BulletItemType> getBulletitem() {
		if (bulletitem == null) {
			bulletitem = new ArrayList<>();
		}
		return this.bulletitem;
	}

	/**
	 * Gets the value of the text property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getText() {
		return text;
	}

	/**
	 * Sets the value of the text property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setText(String value) {
		this.text = value;
	}

}
