//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.sast.api.data.detailedreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * For each severity, there is one attribute:
 * * level:  an integer between 0 and 5 inclusive.  The severity
 * 5 flaws are the most severe; the severity 0 flaws are informational.
 * <p>
 * There is one child element per severity:
 * * category: A category of flaws, with one per category for which there is at
 * least one flaw.
 *
 *
 * <p>Java class for SeverityType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SeverityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="category" type="{https://www.veracode.com/schema/reports/export/1.0}CategoryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="level" use="required" type="{https://www.veracode.com/schema/reports/export/1.0}SeverityValueType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeverityType", namespace = "https://www.veracode.com/schema/reports/export/1.0", propOrder = {
		"category"
})
public class SeverityType {

	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private List<CategoryType> category;
	@XmlAttribute(name = "level", required = true)
	private int level;

	/**
	 * Gets the value of the category property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the category property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getCategory().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CategoryType }
	 *
	 * @return value of the category property, or an empty list if the category property is null
	 */
	public List<CategoryType> getCategory() {
		if (category == null) {
			category = new ArrayList<>();
		}
		return this.category;
	}

	/**
	 * Gets the value of the level property.
	 *
	 * @return value of the level property
	 */
	public int getLevel() {
		return level;
	}

	/**
	 * Sets the value of the level property.
	 *
	 * @param value value to set for the level property
	 */
	public void setLevel(int value) {
		this.level = value;
	}

}
