//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.sast.api.data.detailedreport;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The element describe the details of software composition analysis results.
 * * vulnerable_components: Details of the vulnerable components.
 * * third_party_components: Number of vulnerable third party components.
 * * violate_policy: Policy is violated or not
 * * components_violated_policy: Number of components that violate the
 * policy.
 * * blacklisted_components: Number of blacklisted components.
 * * sca_service_available: true if sca service is available, else set to false
 *
 *
 * <p>Java class for SoftwareCompositionAnalysis complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SoftwareCompositionAnalysis"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vulnerable_components" type="{https://www.veracode.com/schema/reports/export/1.0}VulnerableComponentList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="third_party_components" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="violate_policy" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="components_violated_policy" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="blacklisted_components" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="sca_service_available" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareCompositionAnalysis", namespace = "https://www.veracode.com/schema/reports/export/1.0", propOrder = {
		"vulnerableComponents"
})
public class SoftwareCompositionAnalysis {

	@XmlElement(name = "vulnerable_components", namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private VulnerableComponentList vulnerableComponents;
	@XmlAttribute(name = "third_party_components", required = true)
	private BigInteger thirdPartyComponents;
	@XmlAttribute(name = "violate_policy", required = true)
	private boolean violatePolicy;
	@XmlAttribute(name = "components_violated_policy", required = true)
	private BigInteger componentsViolatedPolicy;
	@XmlAttribute(name = "blacklisted_components")
	private BigInteger blacklistedComponents;
	@XmlAttribute(name = "sca_service_available")
	private Boolean scaServiceAvailable;

	/**
	 * Gets the value of the vulnerableComponents property.
	 *
	 * @return possible object is
	 * {@link VulnerableComponentList }
	 */
	public VulnerableComponentList getVulnerableComponents() {
		return vulnerableComponents;
	}

	/**
	 * Sets the value of the vulnerableComponents property.
	 *
	 * @param value allowed object is
	 *              {@link VulnerableComponentList }
	 */
	public void setVulnerableComponents(VulnerableComponentList value) {
		this.vulnerableComponents = value;
	}

	/**
	 * Gets the value of the thirdPartyComponents property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getThirdPartyComponents() {
		return thirdPartyComponents;
	}

	/**
	 * Sets the value of the thirdPartyComponents property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setThirdPartyComponents(BigInteger value) {
		this.thirdPartyComponents = value;
	}

	/**
	 * Gets the value of the violatePolicy property.
	 *
	 * @return value of the violatePolicy property
	 */
	public boolean isViolatePolicy() {
		return violatePolicy;
	}

	/**
	 * Sets the value of the violatePolicy property.
	 *
	 * @param value value to set for the violatePolicy property
	 */
	public void setViolatePolicy(boolean value) {
		this.violatePolicy = value;
	}

	/**
	 * Gets the value of the componentsViolatedPolicy property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getComponentsViolatedPolicy() {
		return componentsViolatedPolicy;
	}

	/**
	 * Sets the value of the componentsViolatedPolicy property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setComponentsViolatedPolicy(BigInteger value) {
		this.componentsViolatedPolicy = value;
	}

	/**
	 * Gets the value of the blacklistedComponents property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getBlacklistedComponents() {
		return blacklistedComponents;
	}

	/**
	 * Sets the value of the blacklistedComponents property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setBlacklistedComponents(BigInteger value) {
		this.blacklistedComponents = value;
	}

	/**
	 * Gets the value of the scaServiceAvailable property.
	 *
	 * @return possible object is
	 * {@link Boolean }
	 */
	public Boolean isScaServiceAvailable() {
		return scaServiceAvailable;
	}

	/**
	 * Sets the value of the scaServiceAvailable property.
	 *
	 * @param value allowed object is
	 *              {@link Boolean }
	 */
	public void setScaServiceAvailable(Boolean value) {
		this.scaServiceAvailable = value;
	}

}
