/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tracelink.prodsec.lib.veracode.rest.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ApplicationSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-13T02:06:38.897Z")
public class ApplicationSettings {
  @SerializedName("dynamic_scan_approval_not_required")
  private Boolean dynamicScanApprovalNotRequired = null;

  @SerializedName("nextday_consultation_allowed")
  private Boolean nextdayConsultationAllowed = null;

  @SerializedName("sca_enabled")
  private Boolean scaEnabled = null;

  @SerializedName("static_scan_dependencies_allowed")
  private Boolean staticScanDependenciesAllowed = null;

  public ApplicationSettings dynamicScanApprovalNotRequired(Boolean dynamicScanApprovalNotRequired) {
    this.dynamicScanApprovalNotRequired = dynamicScanApprovalNotRequired;
    return this;
  }

   /**
   * Get dynamicScanApprovalNotRequired
   * @return dynamicScanApprovalNotRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isDynamicScanApprovalNotRequired() {
    return dynamicScanApprovalNotRequired;
  }

  public void setDynamicScanApprovalNotRequired(Boolean dynamicScanApprovalNotRequired) {
    this.dynamicScanApprovalNotRequired = dynamicScanApprovalNotRequired;
  }

  public ApplicationSettings nextdayConsultationAllowed(Boolean nextdayConsultationAllowed) {
    this.nextdayConsultationAllowed = nextdayConsultationAllowed;
    return this;
  }

   /**
   * Get nextdayConsultationAllowed
   * @return nextdayConsultationAllowed
  **/
  @ApiModelProperty(value = "")
  public Boolean isNextdayConsultationAllowed() {
    return nextdayConsultationAllowed;
  }

  public void setNextdayConsultationAllowed(Boolean nextdayConsultationAllowed) {
    this.nextdayConsultationAllowed = nextdayConsultationAllowed;
  }

  public ApplicationSettings scaEnabled(Boolean scaEnabled) {
    this.scaEnabled = scaEnabled;
    return this;
  }

   /**
   * Get scaEnabled
   * @return scaEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isScaEnabled() {
    return scaEnabled;
  }

  public void setScaEnabled(Boolean scaEnabled) {
    this.scaEnabled = scaEnabled;
  }

  public ApplicationSettings staticScanDependenciesAllowed(Boolean staticScanDependenciesAllowed) {
    this.staticScanDependenciesAllowed = staticScanDependenciesAllowed;
    return this;
  }

   /**
   * Get staticScanDependenciesAllowed
   * @return staticScanDependenciesAllowed
  **/
  @ApiModelProperty(value = "")
  public Boolean isStaticScanDependenciesAllowed() {
    return staticScanDependenciesAllowed;
  }

  public void setStaticScanDependenciesAllowed(Boolean staticScanDependenciesAllowed) {
    this.staticScanDependenciesAllowed = staticScanDependenciesAllowed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationSettings applicationSettings = (ApplicationSettings) o;
    return Objects.equals(this.dynamicScanApprovalNotRequired, applicationSettings.dynamicScanApprovalNotRequired) &&
        Objects.equals(this.nextdayConsultationAllowed, applicationSettings.nextdayConsultationAllowed) &&
        Objects.equals(this.scaEnabled, applicationSettings.scaEnabled) &&
        Objects.equals(this.staticScanDependenciesAllowed, applicationSettings.staticScanDependenciesAllowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dynamicScanApprovalNotRequired, nextdayConsultationAllowed, scaEnabled, staticScanDependenciesAllowed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationSettings {\n");
    
    sb.append("    dynamicScanApprovalNotRequired: ").append(toIndentedString(dynamicScanApprovalNotRequired)).append("\n");
    sb.append("    nextdayConsultationAllowed: ").append(toIndentedString(nextdayConsultationAllowed)).append("\n");
    sb.append("    scaEnabled: ").append(toIndentedString(scaEnabled)).append("\n");
    sb.append("    staticScanDependenciesAllowed: ").append(toIndentedString(staticScanDependenciesAllowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

