//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:29 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.sast.api.data.sandboxlist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sandbox" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}SandboxType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="sandboxlist_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="account_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="app_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"sandbox"
})
@XmlRootElement(name = "sandboxlist", namespace = "https://analysiscenter.veracode.com/schema/4.0/sandboxlist")
public class Sandboxlist {

	@XmlElement(namespace = "https://analysiscenter.veracode.com/schema/4.0/sandboxlist")
	protected List<SandboxType> sandbox;
	@XmlAttribute(name = "sandboxlist_version", required = true)
	protected String sandboxlistVersion;
	@XmlAttribute(name = "account_id", required = true)
	protected long accountId;
	@XmlAttribute(name = "app_id", required = true)
	protected long appId;

	/**
	 * Gets the value of the sandbox property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the sandbox property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSandbox().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SandboxType }
	 *
	 * @return value of the sandbox property, or an empty list if the sandbox property is null
	 */
	public List<SandboxType> getSandbox() {
		if (sandbox == null) {
			sandbox = new ArrayList<>();
		}
		return this.sandbox;
	}

	/**
	 * Gets the value of the sandboxlistVersion property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSandboxlistVersion() {
		return sandboxlistVersion;
	}

	/**
	 * Sets the value of the sandboxlistVersion property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSandboxlistVersion(String value) {
		this.sandboxlistVersion = value;
	}

	/**
	 * Gets the value of the accountId property.
	 *
	 * @return value of the accountId property
	 */
	public long getAccountId() {
		return accountId;
	}

	/**
	 * Sets the value of the accountId property.
	 *
	 * @param value value to set for the accountId property
	 */
	public void setAccountId(long value) {
		this.accountId = value;
	}

	/**
	 * Gets the value of the appId property.
	 *
	 * @return value of the appId property
	 */
	public long getAppId() {
		return appId;
	}

	/**
	 * Sets the value of the appId property.
	 *
	 * @param value value to set for the appId property
	 */
	public void setAppId(long value) {
		this.appId = value;
	}

}
