//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:29 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.sast.api.data.sandboxlist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The sandbox type element contains the key elements and attributes
 * that reflect the data we store for a sandbox.
 *
 *
 * <p>Java class for SandboxType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SandboxType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="customfield" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}CustomFieldType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="sandbox_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="sandbox_name" use="required" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}LongRequiredTextType" /&gt;
 *       &lt;attribute name="owner" use="required" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}LongRequiredTextType" /&gt;
 *       &lt;attribute name="last_modified" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="expires" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="auto_recreate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SandboxType", namespace = "https://analysiscenter.veracode.com/schema/4.0/sandboxlist", propOrder = {
		"customfield"
})
public class SandboxType {

	@XmlElement(namespace = "https://analysiscenter.veracode.com/schema/4.0/sandboxlist")
	protected List<CustomFieldType> customfield;
	@XmlAttribute(name = "sandbox_id", required = true)
	protected long sandboxId;
	@XmlAttribute(name = "sandbox_name", required = true)
	protected String sandboxName;
	@XmlAttribute(name = "owner", required = true)
	protected String owner;
	@XmlAttribute(name = "last_modified", required = true)
	protected String lastModified;
	@XmlAttribute(name = "expires")
	protected String expires;
	@XmlAttribute(name = "auto_recreate", required = true)
	protected boolean autoRecreate;

	/**
	 * Gets the value of the customfield property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the customfield property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getCustomfield().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CustomFieldType }
	 *
	 * @return value of the customfield property, or an empty list if the customfield property is
	 * null
	 */
	public List<CustomFieldType> getCustomfield() {
		if (customfield == null) {
			customfield = new ArrayList<>();
		}
		return this.customfield;
	}

	/**
	 * Gets the value of the sandboxId property.
	 *
	 * @return value of the sandboxId property
	 */
	public long getSandboxId() {
		return sandboxId;
	}

	/**
	 * Sets the value of the sandboxId property.
	 *
	 * @param value value to set for the sandboxId property
	 */
	public void setSandboxId(long value) {
		this.sandboxId = value;
	}

	/**
	 * Gets the value of the sandboxName property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSandboxName() {
		return sandboxName;
	}

	/**
	 * Sets the value of the sandboxName property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSandboxName(String value) {
		this.sandboxName = value;
	}

	/**
	 * Gets the value of the owner property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * Sets the value of the owner property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setOwner(String value) {
		this.owner = value;
	}

	/**
	 * Gets the value of the lastModified property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLastModified() {
		return lastModified;
	}

	/**
	 * Sets the value of the lastModified property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLastModified(String value) {
		this.lastModified = value;
	}

	/**
	 * Gets the value of the expires property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getExpires() {
		return expires;
	}

	/**
	 * Sets the value of the expires property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setExpires(String value) {
		this.expires = value;
	}

	/**
	 * Gets the value of the autoRecreate property.
	 *
	 * @return value of the autoRecreate property
	 */
	public boolean isAutoRecreate() {
		return autoRecreate;
	}

	/**
	 * Sets the value of the autoRecreate property.
	 *
	 * @param value value to set for the autoRecreate property
	 */
	public void setAutoRecreate(boolean value) {
		this.autoRecreate = value;
	}

}
