//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.dast.api.data.detailedreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * This represents a bullet item within a paragraph.  This has one child
 * element:
 * * text:  The text of the bullet item.
 *
 *
 * <p>Java class for BulletItemType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BulletItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BulletItemType", namespace = "https://www.veracode.com/schema/reports/export/1.0")
public class BulletItemType {

	@XmlAttribute(name = "text", required = true)
	private String text;

	/**
	 * Gets the value of the text property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getText() {
		return text;
	}

	/**
	 * Sets the value of the text property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setText(String value) {
		this.text = value;
	}

}
