//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.dast.api.data.detailedreport;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="static-analysis" type="{https://www.veracode.com/schema/reports/export/1.0}AnalysisType" minOccurs="0"/&gt;
 *         &lt;element name="dynamic-analysis" type="{https://www.veracode.com/schema/reports/export/1.0}AnalysisType" minOccurs="0"/&gt;
 *         &lt;element name="manual-analysis" type="{https://www.veracode.com/schema/reports/export/1.0}ManualAnalysisType" minOccurs="0"/&gt;
 *         &lt;element name="severity" type="{https://www.veracode.com/schema/reports/export/1.0}SeverityType" maxOccurs="6" minOccurs="6"/&gt;
 *         &lt;element name="flaw-status" type="{https://www.veracode.com/schema/reports/export/1.0}FlawStatusType"/&gt;
 *         &lt;element name="customfields" type="{https://www.veracode.com/schema/reports/export/1.0}CustomFieldsType" minOccurs="0"/&gt;
 *         &lt;element name="software_composition_analysis" type="{https://www.veracode.com/schema/reports/export/1.0}SoftwareCompositionAnalysis" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="report_format_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="account_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="app_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="app_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="analysis_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="static_analysis_unit_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="sandbox_name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sandbox_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="first_build_submitted_date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="build_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="vendor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="submitter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="platform" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="assurance_level" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="business_criticality" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="generation_date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="veracode_level" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="total_flaws" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="flaws_not_mitigated" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="teams" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="life_cycle_stage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="planned_deployment_date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="last_update_time" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="is_latest_build" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="policy_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="policy_version" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="policy_compliance_status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="policy_rules_status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="grace_period_expired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="scan_overdue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="any_type_scan_due" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="business_owner" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="business_unit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tags" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="legacy_scan_engine" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"staticAnalysis", "dynamicAnalysis", "manualAnalysis", "severity", "flawStatus", "customfields", "softwareCompositionAnalysis"})
@XmlRootElement(name = "detailedreport", namespace = "https://www.veracode.com/schema/reports/export/1.0")
public class Detailedreport {

	@XmlElement(name = "static-analysis", namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private AnalysisType staticAnalysis;
	@XmlElement(name = "dynamic-analysis", namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private AnalysisType dynamicAnalysis;
	@XmlElement(name = "manual-analysis", namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private ManualAnalysisType manualAnalysis;
	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0", required = true)
	private List<SeverityType> severity;
	@XmlElement(name = "flaw-status", namespace = "https://www.veracode.com/schema/reports/export/1.0", required = true)
	private FlawStatusType flawStatus;
	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private CustomFieldsType customfields;
	@XmlElement(name = "software_composition_analysis", namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private SoftwareCompositionAnalysis softwareCompositionAnalysis;
	@XmlAttribute(name = "report_format_version", required = true)
	private String reportFormatVersion;
	@XmlAttribute(name = "account_id", required = true)
	private long accountId;
	@XmlAttribute(name = "app_name", required = true)
	private String appName;
	@XmlAttribute(name = "app_id", required = true)
	private long appId;
	@XmlAttribute(name = "analysis_id", required = true)
	private long analysisId;
	@XmlAttribute(name = "static_analysis_unit_id", required = true)
	private long staticAnalysisUnitId;
	@XmlAttribute(name = "sandbox_name")
	private String sandboxName;
	@XmlAttribute(name = "sandbox_id", required = true)
	private long sandboxId;
	@XmlAttribute(name = "first_build_submitted_date")
	private String firstBuildSubmittedDate;
	@XmlAttribute(name = "version", required = true)
	private String version;
	@XmlAttribute(name = "build_id", required = true)
	private long buildId;
	@XmlAttribute(name = "vendor")
	private String vendor;
	@XmlAttribute(name = "submitter", required = true)
	private String submitter;
	@XmlAttribute(name = "platform", required = true)
	private String platform;
	@XmlAttribute(name = "assurance_level")
	private BigInteger assuranceLevel;
	@XmlAttribute(name = "business_criticality")
	private BigInteger businessCriticality;
	@XmlAttribute(name = "generation_date", required = true)
	private String generationDate;
	@XmlAttribute(name = "veracode_level", required = true)
	private String veracodeLevel;
	@XmlAttribute(name = "total_flaws")
	private BigInteger totalFlaws;
	@XmlAttribute(name = "flaws_not_mitigated")
	private BigInteger flawsNotMitigated;
	@XmlAttribute(name = "teams", required = true)
	private String teams;
	@XmlAttribute(name = "life_cycle_stage", required = true)
	private String lifeCycleStage;
	@XmlAttribute(name = "planned_deployment_date")
	private String plannedDeploymentDate;
	@XmlAttribute(name = "last_update_time", required = true)
	private String lastUpdateTime;
	@XmlAttribute(name = "is_latest_build", required = true)
	private boolean isLatestBuild;
	@XmlAttribute(name = "policy_name", required = true)
	private String policyName;
	@XmlAttribute(name = "policy_version", required = true)
	private BigInteger policyVersion;
	@XmlAttribute(name = "policy_compliance_status", required = true)
	private String policyComplianceStatus;
	@XmlAttribute(name = "policy_rules_status", required = true)
	private String policyRulesStatus;
	@XmlAttribute(name = "grace_period_expired", required = true)
	private boolean gracePeriodExpired;
	@XmlAttribute(name = "scan_overdue", required = true)
	private String scanOverdue;
	@XmlAttribute(name = "any_type_scan_due")
	private String anyTypeScanDue;
	@XmlAttribute(name = "business_owner")
	private String businessOwner;
	@XmlAttribute(name = "business_unit")
	private String businessUnit;
	@XmlAttribute(name = "tags")
	private String tags;
	@XmlAttribute(name = "legacy_scan_engine")
	private Boolean legacyScanEngine;

	/**
	 * Gets the value of the staticAnalysis property.
	 *
	 * @return possible object is
	 * {@link AnalysisType }
	 */
	public AnalysisType getStaticAnalysis() {
		return staticAnalysis;
	}

	/**
	 * Sets the value of the staticAnalysis property.
	 *
	 * @param value allowed object is
	 *              {@link AnalysisType }
	 */
	public void setStaticAnalysis(AnalysisType value) {
		this.staticAnalysis = value;
	}

	/**
	 * Gets the value of the dynamicAnalysis property.
	 *
	 * @return possible object is
	 * {@link AnalysisType }
	 */
	public AnalysisType getDynamicAnalysis() {
		return dynamicAnalysis;
	}

	/**
	 * Sets the value of the dynamicAnalysis property.
	 *
	 * @param value allowed object is
	 *              {@link AnalysisType }
	 */
	public void setDynamicAnalysis(AnalysisType value) {
		this.dynamicAnalysis = value;
	}

	/**
	 * Gets the value of the manualAnalysis property.
	 *
	 * @return possible object is
	 * {@link ManualAnalysisType }
	 */
	public ManualAnalysisType getManualAnalysis() {
		return manualAnalysis;
	}

	/**
	 * Sets the value of the manualAnalysis property.
	 *
	 * @param value allowed object is
	 *              {@link ManualAnalysisType }
	 */
	public void setManualAnalysis(ManualAnalysisType value) {
		this.manualAnalysis = value;
	}

	/**
	 * Gets the value of the severity property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the severity property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getSeverity().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SeverityType }
	 *
	 * @return value of the severity property, or an empty list if the severity property is null
	 */
	public List<SeverityType> getSeverity() {
		if (severity == null) {
			severity = new ArrayList<>();
		}
		return this.severity;
	}

	/**
	 * Sets the value of the severity property.
	 *
	 * @param severity value to set for the severity property
	 */
	public void setSeverity(List<SeverityType> severity) {
		this.severity = severity;
	}

	/**
	 * Gets the value of the flawStatus property.
	 *
	 * @return possible object is
	 * {@link FlawStatusType }
	 */
	public FlawStatusType getFlawStatus() {
		return flawStatus;
	}

	/**
	 * Sets the value of the flawStatus property.
	 *
	 * @param value allowed object is
	 *              {@link FlawStatusType }
	 */
	public void setFlawStatus(FlawStatusType value) {
		this.flawStatus = value;
	}

	/**
	 * Gets the value of the customfields property.
	 *
	 * @return possible object is
	 * {@link CustomFieldsType }
	 */
	public CustomFieldsType getCustomfields() {
		return customfields;
	}

	/**
	 * Sets the value of the customfields property.
	 *
	 * @param value allowed object is
	 *              {@link CustomFieldsType }
	 */
	public void setCustomfields(CustomFieldsType value) {
		this.customfields = value;
	}

	/**
	 * Gets the value of the softwareCompositionAnalysis property.
	 *
	 * @return possible object is
	 * {@link SoftwareCompositionAnalysis }
	 */
	public SoftwareCompositionAnalysis getSoftwareCompositionAnalysis() {
		return softwareCompositionAnalysis;
	}

	/**
	 * Sets the value of the softwareCompositionAnalysis property.
	 *
	 * @param value allowed object is
	 *              {@link SoftwareCompositionAnalysis }
	 */
	public void setSoftwareCompositionAnalysis(SoftwareCompositionAnalysis value) {
		this.softwareCompositionAnalysis = value;
	}

	/**
	 * Gets the value of the reportFormatVersion property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getReportFormatVersion() {
		return reportFormatVersion;
	}

	/**
	 * Sets the value of the reportFormatVersion property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setReportFormatVersion(String value) {
		this.reportFormatVersion = value;
	}

	/**
	 * Gets the value of the accountId property.
	 *
	 * @return value of the accountId property
	 */
	public long getAccountId() {
		return accountId;
	}

	/**
	 * Sets the value of the accountId property.
	 *
	 * @param value value to set for the accountId property
	 */
	public void setAccountId(long value) {
		this.accountId = value;
	}

	/**
	 * Gets the value of the appName property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * Sets the value of the appName property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAppName(String value) {
		this.appName = value;
	}

	/**
	 * Gets the value of the appId property.
	 *
	 * @return value of the appId property
	 */
	public long getAppId() {
		return appId;
	}

	/**
	 * Sets the value of the appId property.
	 *
	 * @param value value to set for the appId property
	 */
	public void setAppId(long value) {
		this.appId = value;
	}

	/**
	 * Gets the value of the analysisId property.
	 *
	 * @return value of the analysisId property
	 */
	public long getAnalysisId() {
		return analysisId;
	}

	/**
	 * Sets the value of the analysisId property.
	 *
	 * @param value value to set for the analysisId property
	 */
	public void setAnalysisId(long value) {
		this.analysisId = value;
	}

	/**
	 * Gets the value of the staticAnalysisUnitId property.
	 *
	 * @return value of the staticAnalysisUnitId property
	 */
	public long getStaticAnalysisUnitId() {
		return staticAnalysisUnitId;
	}

	/**
	 * Sets the value of the staticAnalysisUnitId property.
	 *
	 * @param value value to set for the staticAnalysisUnitId property
	 */
	public void setStaticAnalysisUnitId(long value) {
		this.staticAnalysisUnitId = value;
	}

	/**
	 * Gets the value of the sandboxName property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSandboxName() {
		return sandboxName;
	}

	/**
	 * Sets the value of the sandboxName property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSandboxName(String value) {
		this.sandboxName = value;
	}

	/**
	 * Gets the value of the sandboxId property.
	 *
	 * @return value of the sandboxId property
	 */
	public long getSandboxId() {
		return sandboxId;
	}

	/**
	 * Sets the value of the sandboxId property.
	 *
	 * @param value value to set for the sandboxId property
	 */
	public void setSandboxId(long value) {
		this.sandboxId = value;
	}

	/**
	 * Gets the value of the firstBuildSubmittedDate property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getFirstBuildSubmittedDate() {
		return firstBuildSubmittedDate;
	}

	/**
	 * Sets the value of the firstBuildSubmittedDate property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setFirstBuildSubmittedDate(String value) {
		this.firstBuildSubmittedDate = value;
	}

	/**
	 * Gets the value of the version property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the buildId property.
	 *
	 * @return value of the buildId property
	 */
	public long getBuildId() {
		return buildId;
	}

	/**
	 * Sets the value of the buildId property.
	 *
	 * @param value value to set for the buildId property
	 */
	public void setBuildId(long value) {
		this.buildId = value;
	}

	/**
	 * Gets the value of the vendor property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getVendor() {
		return vendor;
	}

	/**
	 * Sets the value of the vendor property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setVendor(String value) {
		this.vendor = value;
	}

	/**
	 * Gets the value of the submitter property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getSubmitter() {
		return submitter;
	}

	/**
	 * Sets the value of the submitter property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setSubmitter(String value) {
		this.submitter = value;
	}

	/**
	 * Gets the value of the platform property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPlatform() {
		return platform;
	}

	/**
	 * Sets the value of the platform property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPlatform(String value) {
		this.platform = value;
	}

	/**
	 * Gets the value of the assuranceLevel property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getAssuranceLevel() {
		return assuranceLevel;
	}

	/**
	 * Sets the value of the assuranceLevel property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setAssuranceLevel(BigInteger value) {
		this.assuranceLevel = value;
	}

	/**
	 * Gets the value of the businessCriticality property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getBusinessCriticality() {
		return businessCriticality;
	}

	/**
	 * Sets the value of the businessCriticality property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setBusinessCriticality(BigInteger value) {
		this.businessCriticality = value;
	}

	/**
	 * Gets the value of the generationDate property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getGenerationDate() {
		return generationDate;
	}

	/**
	 * Sets the value of the generationDate property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setGenerationDate(String value) {
		this.generationDate = value;
	}

	/**
	 * Gets the value of the veracodeLevel property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getVeracodeLevel() {
		return veracodeLevel;
	}

	/**
	 * Sets the value of the veracodeLevel property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setVeracodeLevel(String value) {
		this.veracodeLevel = value;
	}

	/**
	 * Gets the value of the totalFlaws property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getTotalFlaws() {
		return totalFlaws;
	}

	/**
	 * Sets the value of the totalFlaws property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setTotalFlaws(BigInteger value) {
		this.totalFlaws = value;
	}

	/**
	 * Gets the value of the flawsNotMitigated property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getFlawsNotMitigated() {
		return flawsNotMitigated;
	}

	/**
	 * Sets the value of the flawsNotMitigated property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setFlawsNotMitigated(BigInteger value) {
		this.flawsNotMitigated = value;
	}

	/**
	 * Gets the value of the teams property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getTeams() {
		return teams;
	}

	/**
	 * Sets the value of the teams property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setTeams(String value) {
		this.teams = value;
	}

	/**
	 * Gets the value of the lifeCycleStage property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLifeCycleStage() {
		return lifeCycleStage;
	}

	/**
	 * Sets the value of the lifeCycleStage property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLifeCycleStage(String value) {
		this.lifeCycleStage = value;
	}

	/**
	 * Gets the value of the plannedDeploymentDate property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPlannedDeploymentDate() {
		return plannedDeploymentDate;
	}

	/**
	 * Sets the value of the plannedDeploymentDate property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPlannedDeploymentDate(String value) {
		this.plannedDeploymentDate = value;
	}

	/**
	 * Gets the value of the lastUpdateTime property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * Sets the value of the lastUpdateTime property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setLastUpdateTime(String value) {
		this.lastUpdateTime = value;
	}

	/**
	 * Gets the value of the isLatestBuild property.
	 *
	 * @return value of the isLatestBuild property
	 */
	public boolean isIsLatestBuild() {
		return isLatestBuild;
	}

	/**
	 * Sets the value of the isLatestBuild property.
	 *
	 * @param value value to set for the isLatestBuild property
	 */
	public void setIsLatestBuild(boolean value) {
		this.isLatestBuild = value;
	}

	/**
	 * Gets the value of the policyName property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPolicyName() {
		return policyName;
	}

	/**
	 * Sets the value of the policyName property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPolicyName(String value) {
		this.policyName = value;
	}

	/**
	 * Gets the value of the policyVersion property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getPolicyVersion() {
		return policyVersion;
	}

	/**
	 * Sets the value of the policyVersion property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setPolicyVersion(BigInteger value) {
		this.policyVersion = value;
	}

	/**
	 * Gets the value of the policyComplianceStatus property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPolicyComplianceStatus() {
		return policyComplianceStatus;
	}

	/**
	 * Sets the value of the policyComplianceStatus property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPolicyComplianceStatus(String value) {
		this.policyComplianceStatus = value;
	}

	/**
	 * Gets the value of the policyRulesStatus property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPolicyRulesStatus() {
		return policyRulesStatus;
	}

	/**
	 * Sets the value of the policyRulesStatus property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPolicyRulesStatus(String value) {
		this.policyRulesStatus = value;
	}

	/**
	 * Gets the value of the gracePeriodExpired property.
	 *
	 * @return value of the gracePeriodExpired property
	 */
	public boolean isGracePeriodExpired() {
		return gracePeriodExpired;
	}

	/**
	 * Sets the value of the gracePeriodExpired property.
	 *
	 * @param value value to set for the gracePeriodExpired property
	 */
	public void setGracePeriodExpired(boolean value) {
		this.gracePeriodExpired = value;
	}

	/**
	 * Gets the value of the scanOverdue property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getScanOverdue() {
		return scanOverdue;
	}

	/**
	 * Sets the value of the scanOverdue property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setScanOverdue(String value) {
		this.scanOverdue = value;
	}

	/**
	 * Gets the value of the anyTypeScanDue property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAnyTypeScanDue() {
		return anyTypeScanDue;
	}

	/**
	 * Sets the value of the anyTypeScanDue property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAnyTypeScanDue(String value) {
		this.anyTypeScanDue = value;
	}

	/**
	 * Gets the value of the businessOwner property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getBusinessOwner() {
		return businessOwner;
	}

	/**
	 * Sets the value of the businessOwner property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setBusinessOwner(String value) {
		this.businessOwner = value;
	}

	/**
	 * Gets the value of the businessUnit property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getBusinessUnit() {
		return businessUnit;
	}

	/**
	 * Sets the value of the businessUnit property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setBusinessUnit(String value) {
		this.businessUnit = value;
	}

	/**
	 * Gets the value of the tags property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * Sets the value of the tags property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setTags(String value) {
		this.tags = value;
	}

	/**
	 * Gets the value of the legacyScanEngine property.
	 *
	 * @return possible object is
	 * {@link Boolean }
	 */
	public Boolean isLegacyScanEngine() {
		return legacyScanEngine;
	}

	/**
	 * Sets the value of the legacyScanEngine property.
	 *
	 * @param value allowed object is
	 *              {@link Boolean }
	 */
	public void setLegacyScanEngine(Boolean value) {
		this.legacyScanEngine = value;
	}

}
