//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.dast.api.data.detailedreport;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       Each module element has the following attributes:
 *       
 *       * name:  The name of the module.  If the module represents dynamic
 *         analysis, the name is blank.
 *       * compiler:  The compiler that compiled the module.  This value is
 *         blank for dynamic analysis module elements.
 *       * os:  The name of the operating system for which the module is
 *         targeted.  This value is blank for dynamic analysis module elements.
 *       * architecture:  The name of the architecture for which the module is
 *         targeted.  This value is blank for dynamic analysis module elements.
 *       * loc:  The lines of codes. This value is blank for dynamic analysis or non-debug modules.
 *       * score:  A module-specific score, which contributes toward the analysis scores.
 *       * numflawssev0:  The number of severity-0 flaws.  (This is the lowest
 *         flaw severity and usually referred to as informational.)
 *       * numflawssev1:  The number of severity-1 flaws.
 *       * numflawssev2:  The number of severity-2 flaws.
 *       * numflawssev3:  The number of severity-3 flaws.
 *       * numflawssev4:  The number of severity-4 flaws.
 *       * numflawssev5:  The number of severity-5 flaws.  (This is the highest
 *         flaw severity.)
 *     
 * 
 * <p>Java class for ModuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="compiler" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="os" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="architecture" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="loc" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numflawssev0" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numflawssev1" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numflawssev2" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numflawssev3" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numflawssev4" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="numflawssev5" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="target_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="domain" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="approxlinecount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleType", namespace = "https://www.veracode.com/schema/reports/export/1.0")
public class ModuleType {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "compiler", required = true)
    protected String compiler;
    @XmlAttribute(name = "os", required = true)
    protected String os;
    @XmlAttribute(name = "architecture", required = true)
    protected String architecture;
    @XmlAttribute(name = "loc")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger loc;
    @XmlAttribute(name = "score", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger score;
    @XmlAttribute(name = "numflawssev0", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev0;
    @XmlAttribute(name = "numflawssev1", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev1;
    @XmlAttribute(name = "numflawssev2", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev2;
    @XmlAttribute(name = "numflawssev3", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev3;
    @XmlAttribute(name = "numflawssev4", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev4;
    @XmlAttribute(name = "numflawssev5", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numflawssev5;
    @XmlAttribute(name = "target_url")
    protected String targetUrl;
    @XmlAttribute(name = "domain")
    protected String domain;
    @XmlAttribute(name = "approxlinecount")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger approxlinecount;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the compiler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompiler() {
        return compiler;
    }

    /**
     * Sets the value of the compiler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompiler(String value) {
        this.compiler = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOs() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOs(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the architecture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchitecture() {
        return architecture;
    }

    /**
     * Sets the value of the architecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchitecture(String value) {
        this.architecture = value;
    }

    /**
     * Gets the value of the loc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoc() {
        return loc;
    }

    /**
     * Sets the value of the loc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoc(BigInteger value) {
        this.loc = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScore(BigInteger value) {
        this.score = value;
    }

    /**
     * Gets the value of the numflawssev0 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumflawssev0() {
        return numflawssev0;
    }

    /**
     * Sets the value of the numflawssev0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumflawssev0(BigInteger value) {
        this.numflawssev0 = value;
    }

    /**
     * Gets the value of the numflawssev1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumflawssev1() {
        return numflawssev1;
    }

    /**
     * Sets the value of the numflawssev1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumflawssev1(BigInteger value) {
        this.numflawssev1 = value;
    }

    /**
     * Gets the value of the numflawssev2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumflawssev2() {
        return numflawssev2;
    }

    /**
     * Sets the value of the numflawssev2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumflawssev2(BigInteger value) {
        this.numflawssev2 = value;
    }

    /**
     * Gets the value of the numflawssev3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumflawssev3() {
        return numflawssev3;
    }

    /**
     * Sets the value of the numflawssev3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumflawssev3(BigInteger value) {
        this.numflawssev3 = value;
    }

    /**
     * Gets the value of the numflawssev4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumflawssev4() {
        return numflawssev4;
    }

    /**
     * Sets the value of the numflawssev4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumflawssev4(BigInteger value) {
        this.numflawssev4 = value;
    }

    /**
     * Gets the value of the numflawssev5 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumflawssev5() {
        return numflawssev5;
    }

    /**
     * Sets the value of the numflawssev5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumflawssev5(BigInteger value) {
        this.numflawssev5 = value;
    }

    /**
     * Gets the value of the targetUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * Sets the value of the targetUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetUrl(String value) {
        this.targetUrl = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the approxlinecount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApproxlinecount() {
        return approxlinecount;
    }

    /**
     * Sets the value of the approxlinecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApproxlinecount(BigInteger value) {
        this.approxlinecount = value;
    }

}
