//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.plugin.veracode.dast.api.data.detailedreport;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyRuleType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="PolicyRuleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Disallow Vulnerabilities by Severity"/&gt;
 *     &lt;enumeration value="Disallow CVSS Score"/&gt;
 *     &lt;enumeration value="Disallow Component Blacklist"/&gt;
 *     &lt;enumeration value="Disallow Component by License Risk"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "PolicyRuleType", namespace = "https://www.veracode.com/schema/reports/export/1.0")
@XmlEnum
public enum PolicyRuleType {

	@XmlEnumValue("Disallow Vulnerabilities by Severity")
	DISALLOW_VULNERABILITIES_BY_SEVERITY("Disallow Vulnerabilities by Severity"),
	@XmlEnumValue("Disallow CVSS Score")
	DISALLOW_CVSS_SCORE("Disallow CVSS Score"),
	@XmlEnumValue("Disallow Component Blacklist")
	DISALLOW_COMPONENT_BLACKLIST("Disallow Component Blacklist"),
	@XmlEnumValue("Disallow Component by License Risk")
	DISALLOW_COMPONENT_BY_LICENSE_RISK("Disallow Component by License Risk");
	private final String value;

	PolicyRuleType(String v) {
		value = v;
	}

	/**
	 * Gets the value for this policy rule type.
	 *
	 * @return the policy rule type value
	 */
	public String value() {
		return value;
	}

	/**
	 * Gets the {@link PolicyRuleType} associated with the given value.
	 *
	 * @param v the value to get a policy rule type for
	 * @return the policy rule type
	 */
	public static PolicyRuleType fromValue(String v) {
		for (PolicyRuleType c : PolicyRuleType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
