/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * AppCustomFieldValue
 */
public class AppCustomFieldValue {
	@SerializedName("app_custom_field_name")
	private AppCustomFieldName appCustomFieldName = null;

	@SerializedName("created")
	private String created = null;

	@SerializedName("field_name_id")
	private Integer fieldNameId = null;

	@SerializedName("id")
	private Integer id = null;

	@SerializedName("value")
	private String value = null;

	public AppCustomFieldValue appCustomFieldName(AppCustomFieldName appCustomFieldName) {
		this.appCustomFieldName = appCustomFieldName;
		return this;
	}

	/**
	 * Get appCustomFieldName
	 * 
	 * @return appCustomFieldName
	 **/
	@ApiModelProperty(value = "")
	public AppCustomFieldName getAppCustomFieldName() {
		return appCustomFieldName;
	}

	public void setAppCustomFieldName(AppCustomFieldName appCustomFieldName) {
		this.appCustomFieldName = appCustomFieldName;
	}

	/**
	 * The date and time when the application was created. The date/time format is
	 * per RFC3339 and ISO-8601, and the timezone is UTC. Example:
	 * 2019-04-12T23:20:50.52Z.
	 * 
	 * @return created
	 **/
	@ApiModelProperty(value = "The date and time when the application was created. The date/time format is per RFC3339 and ISO-8601, and the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.")
	public String getCreated() {
		return created;
	}

	public AppCustomFieldValue fieldNameId(Integer fieldNameId) {
		this.fieldNameId = fieldNameId;
		return this;
	}

	/**
	 * Get fieldNameId
	 * 
	 * @return fieldNameId
	 **/
	@ApiModelProperty(value = "")
	public Integer getFieldNameId() {
		return fieldNameId;
	}

	public void setFieldNameId(Integer fieldNameId) {
		this.fieldNameId = fieldNameId;
	}

	public AppCustomFieldValue id(Integer id) {
		this.id = id;
		return this;
	}

	/**
	 * Unique identifier of the category.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique identifier of the category.")
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AppCustomFieldValue value(String value) {
		this.value = value;
		return this;
	}

	/**
	 * Get value
	 * 
	 * @return value
	 **/
	@ApiModelProperty(value = "")
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppCustomFieldValue appCustomFieldValue = (AppCustomFieldValue) o;
		return Objects.equals(this.appCustomFieldName, appCustomFieldValue.appCustomFieldName)
				&& Objects.equals(this.created, appCustomFieldValue.created)
				&& Objects.equals(this.fieldNameId, appCustomFieldValue.fieldNameId)
				&& Objects.equals(this.id, appCustomFieldValue.id)
				&& Objects.equals(this.value, appCustomFieldValue.value);
	}

	@Override
	public int hashCode() {
		return Objects.hash(appCustomFieldName, created, fieldNameId, id, value);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppCustomFieldValue {\n");

		sb.append("    appCustomFieldName: ").append(toIndentedString(appCustomFieldName)).append("\n");
		sb.append("    created: ").append(toIndentedString(created)).append("\n");
		sb.append("    fieldNameId: ").append(toIndentedString(fieldNameId)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
