/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * AppCustomFieldName
 */
public class AppCustomFieldName {
	@SerializedName("created")
	private String created = null;

	@SerializedName("id")
	private Integer id = null;

	@SerializedName("modified")
	private String modified = null;

	@SerializedName("name")
	private String name = null;

	@SerializedName("organization_id")
	private Integer organizationId = null;

	@SerializedName("sort_order")
	private Integer sortOrder = null;

	/**
	 * The date and time when the application was created. The date/time format is
	 * per RFC3339 and ISO-8601, and the timezone is UTC. Example:
	 * 2019-04-12T23:20:50.52Z.
	 * 
	 * @return created
	 **/
	@ApiModelProperty(value = "The date and time when the application was created. The date/time format is per RFC3339 and ISO-8601, and the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.")
	public String getCreated() {
		return created;
	}

	/**
	 * Unique identifier of the category.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Unique identifier of the category.")
	public Integer getId() {
		return id;
	}

	/**
	 * The date and time when the application was modified. The date/time format is
	 * per RFC3339 and ISO-8601, and the timezone is UTC. Example:
	 * 2019-04-12T23:20:50.52Z.
	 * 
	 * @return modified
	 **/
	@ApiModelProperty(value = "The date and time when the application was modified. The date/time format is per RFC3339 and ISO-8601, and the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.")
	public String getModified() {
		return modified;
	}

	/**
	 * Get name
	 * 
	 * @return name
	 **/
	@ApiModelProperty(value = "")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get organizationId
	 * 
	 * @return organizationId
	 **/
	@ApiModelProperty(value = "")
	public Integer getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	/**
	 * Get sortOrder
	 * 
	 * @return sortOrder
	 **/
	@ApiModelProperty(value = "")
	public Integer getSortOrder() {
		return sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppCustomFieldName appCustomFieldName = (AppCustomFieldName) o;
		return Objects.equals(this.created, appCustomFieldName.created)
				&& Objects.equals(this.id, appCustomFieldName.id)
				&& Objects.equals(this.modified, appCustomFieldName.modified)
				&& Objects.equals(this.name, appCustomFieldName.name)
				&& Objects.equals(this.organizationId, appCustomFieldName.organizationId)
				&& Objects.equals(this.sortOrder, appCustomFieldName.sortOrder);
	}

	@Override
	public int hashCode() {
		return Objects.hash(created, id, modified, name, organizationId, sortOrder);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppCustomFieldName {\n");

		sb.append("    created: ").append(toIndentedString(created)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
		sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
