/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModelProperty;

/**
 * ApplicationProfile
 */
public class ApplicationProfile {
	@SerializedName("archer_app_name")
	private String archerAppName = null;

	/**
	 * Gets or Sets businessCriticality
	 */
	@JsonAdapter(BusinessCriticalityEnum.Adapter.class)
	public enum BusinessCriticalityEnum {
		VERY_HIGH("VERY_HIGH"),

		HIGH("HIGH"),

		MEDIUM("MEDIUM"),

		LOW("LOW"),

		VERY_LOW("VERY_LOW");

		private String value;

		BusinessCriticalityEnum(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		public static BusinessCriticalityEnum fromValue(String text) {
			for (BusinessCriticalityEnum b : BusinessCriticalityEnum.values()) {
				if (String.valueOf(b.value).equals(text)) {
					return b;
				}
			}
			return null;
		}

		public static class Adapter extends TypeAdapter<BusinessCriticalityEnum> {
			@Override
			public void write(final JsonWriter jsonWriter, final BusinessCriticalityEnum enumeration)
					throws IOException {
				jsonWriter.value(enumeration.getValue());
			}

			@Override
			public BusinessCriticalityEnum read(final JsonReader jsonReader) throws IOException {
				String value = jsonReader.nextString();
				return BusinessCriticalityEnum.fromValue(String.valueOf(value));
			}
		}
	}

	@SerializedName("business_criticality")
	private BusinessCriticalityEnum businessCriticality = null;

	@SerializedName("business_owners")
	private List<BusinessOwner> businessOwners = null;

	@SerializedName("business_unit")
	private BusinessUnit businessUnit = null;

	@SerializedName("custom_field_values")
	private List<AppCustomFieldValue> customFieldValues = null;

	@SerializedName("custom_fields")
	private List<CustomNameValue> customFields = null;

	@SerializedName("description")
	private String description = null;

	@SerializedName("name")
	private String name = null;

	@SerializedName("policies")
	private List<AppPolicy> policies = null;

	@SerializedName("settings")
	private ApplicationSettings settings = null;

	@SerializedName("tags")
	private String tags = null;

	@SerializedName("teams")
	private List<AppTeam> teams = null;

	public ApplicationProfile archerAppName(String archerAppName) {
		this.archerAppName = archerAppName;
		return this;
	}

	/**
	 * Get archerAppName
	 * 
	 * @return archerAppName
	 **/
	@ApiModelProperty(value = "")
	public String getArcherAppName() {
		return archerAppName;
	}

	public void setArcherAppName(String archerAppName) {
		this.archerAppName = archerAppName;
	}

	public ApplicationProfile businessCriticality(BusinessCriticalityEnum businessCriticality) {
		this.businessCriticality = businessCriticality;
		return this;
	}

	/**
	 * Get businessCriticality
	 * 
	 * @return businessCriticality
	 **/
	@ApiModelProperty(value = "")
	public BusinessCriticalityEnum getBusinessCriticality() {
		return businessCriticality;
	}

	public void setBusinessCriticality(BusinessCriticalityEnum businessCriticality) {
		this.businessCriticality = businessCriticality;
	}

	public ApplicationProfile businessOwners(List<BusinessOwner> businessOwners) {
		this.businessOwners = businessOwners;
		return this;
	}

	public ApplicationProfile addBusinessOwnersItem(BusinessOwner businessOwnersItem) {
		if (this.businessOwners == null) {
			this.businessOwners = new ArrayList<BusinessOwner>();
		}
		this.businessOwners.add(businessOwnersItem);
		return this;
	}

	/**
	 * Get businessOwners
	 * 
	 * @return businessOwners
	 **/
	@ApiModelProperty(value = "")
	public List<BusinessOwner> getBusinessOwners() {
		return businessOwners;
	}

	public void setBusinessOwners(List<BusinessOwner> businessOwners) {
		this.businessOwners = businessOwners;
	}

	public ApplicationProfile businessUnit(BusinessUnit businessUnit) {
		this.businessUnit = businessUnit;
		return this;
	}

	/**
	 * Get businessUnit
	 * 
	 * @return businessUnit
	 **/
	@ApiModelProperty(value = "")
	public BusinessUnit getBusinessUnit() {
		return businessUnit;
	}

	public void setBusinessUnit(BusinessUnit businessUnit) {
		this.businessUnit = businessUnit;
	}

	public ApplicationProfile customFieldValues(List<AppCustomFieldValue> customFieldValues) {
		this.customFieldValues = customFieldValues;
		return this;
	}

	public ApplicationProfile addCustomFieldValuesItem(AppCustomFieldValue customFieldValuesItem) {
		if (this.customFieldValues == null) {
			this.customFieldValues = new ArrayList<AppCustomFieldValue>();
		}
		this.customFieldValues.add(customFieldValuesItem);
		return this;
	}

	/**
	 * Get customFieldValues
	 * 
	 * @return customFieldValues
	 **/
	@ApiModelProperty(value = "")
	public List<AppCustomFieldValue> getCustomFieldValues() {
		return customFieldValues;
	}

	public void setCustomFieldValues(List<AppCustomFieldValue> customFieldValues) {
		this.customFieldValues = customFieldValues;
	}

	public ApplicationProfile customFields(List<CustomNameValue> customFields) {
		this.customFields = customFields;
		return this;
	}

	public ApplicationProfile addCustomFieldsItem(CustomNameValue customFieldsItem) {
		if (this.customFields == null) {
			this.customFields = new ArrayList<CustomNameValue>();
		}
		this.customFields.add(customFieldsItem);
		return this;
	}

	/**
	 * Get customFields
	 * 
	 * @return customFields
	 **/
	@ApiModelProperty(value = "")
	public List<CustomNameValue> getCustomFields() {
		return customFields;
	}

	public void setCustomFields(List<CustomNameValue> customFields) {
		this.customFields = customFields;
	}

	public ApplicationProfile description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * Get description
	 * 
	 * @return description
	 **/
	@ApiModelProperty(value = "")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public ApplicationProfile name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * 
	 * @return name
	 **/
	@ApiModelProperty(value = "")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ApplicationProfile policies(List<AppPolicy> policies) {
		this.policies = policies;
		return this;
	}

	public ApplicationProfile addPoliciesItem(AppPolicy policiesItem) {
		if (this.policies == null) {
			this.policies = new ArrayList<AppPolicy>();
		}
		this.policies.add(policiesItem);
		return this;
	}

	/**
	 * Get policies
	 * 
	 * @return policies
	 **/
	@ApiModelProperty(value = "")
	public List<AppPolicy> getPolicies() {
		return policies;
	}

	public void setPolicies(List<AppPolicy> policies) {
		this.policies = policies;
	}

	public ApplicationProfile settings(ApplicationSettings settings) {
		this.settings = settings;
		return this;
	}

	/**
	 * Get settings
	 * 
	 * @return settings
	 **/
	@ApiModelProperty(value = "")
	public ApplicationSettings getSettings() {
		return settings;
	}

	public void setSettings(ApplicationSettings settings) {
		this.settings = settings;
	}

	public ApplicationProfile tags(String tags) {
		this.tags = tags;
		return this;
	}

	/**
	 * Get tags
	 * 
	 * @return tags
	 **/
	@ApiModelProperty(value = "")
	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public ApplicationProfile teams(List<AppTeam> teams) {
		this.teams = teams;
		return this;
	}

	public ApplicationProfile addTeamsItem(AppTeam teamsItem) {
		if (this.teams == null) {
			this.teams = new ArrayList<AppTeam>();
		}
		this.teams.add(teamsItem);
		return this;
	}

	/**
	 * Get teams
	 * 
	 * @return teams
	 **/
	@ApiModelProperty(value = "")
	public List<AppTeam> getTeams() {
		return teams;
	}

	public void setTeams(List<AppTeam> teams) {
		this.teams = teams;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ApplicationProfile applicationProfile = (ApplicationProfile) o;
		return Objects.equals(this.archerAppName, applicationProfile.archerAppName)
				&& Objects.equals(this.businessCriticality, applicationProfile.businessCriticality)
				&& Objects.equals(this.businessOwners, applicationProfile.businessOwners)
				&& Objects.equals(this.businessUnit, applicationProfile.businessUnit)
				&& Objects.equals(this.customFieldValues, applicationProfile.customFieldValues)
				&& Objects.equals(this.customFields, applicationProfile.customFields)
				&& Objects.equals(this.description, applicationProfile.description)
				&& Objects.equals(this.name, applicationProfile.name)
				&& Objects.equals(this.policies, applicationProfile.policies)
				&& Objects.equals(this.settings, applicationProfile.settings)
				&& Objects.equals(this.tags, applicationProfile.tags)
				&& Objects.equals(this.teams, applicationProfile.teams);
	}

	@Override
	public int hashCode() {
		return Objects.hash(archerAppName, businessCriticality, businessOwners, businessUnit, customFieldValues,
				customFields, description, name, policies, settings, tags, teams);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ApplicationProfile {\n");

		sb.append("    archerAppName: ").append(toIndentedString(archerAppName)).append("\n");
		sb.append("    businessCriticality: ").append(toIndentedString(businessCriticality)).append("\n");
		sb.append("    businessOwners: ").append(toIndentedString(businessOwners)).append("\n");
		sb.append("    businessUnit: ").append(toIndentedString(businessUnit)).append("\n");
		sb.append("    customFieldValues: ").append(toIndentedString(customFieldValues)).append("\n");
		sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
		sb.append("    description: ").append(toIndentedString(description)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
		sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
		sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
		sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
