/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Application
 */
public class Application {
	@SerializedName("app_profile_url")
	private String appProfileUrl = null;

	@SerializedName("created")
	private String created = null;

	@SerializedName("guid")
	private String guid = null;

	@SerializedName("id")
	private Integer id = null;

	@SerializedName("last_completed_scan_date")
	private String lastCompletedScanDate = null;

	@SerializedName("modified")
	private String modified = null;

	@SerializedName("oid")
	private Integer oid = null;

	@SerializedName("organization_id")
	private Integer organizationId = null;

	@SerializedName("profile")
	private ApplicationProfile profile = null;

	@SerializedName("results_url")
	private String resultsUrl = null;

	@SerializedName("scans")
	private List<ApplicationScan> scans = null;

	/**
	 * Unique path to the application profile.
	 * 
	 * @return appProfileUrl
	 **/
	@ApiModelProperty(value = "Unique path to the application profile.")
	public String getAppProfileUrl() {
		return appProfileUrl;
	}

	/**
	 * The date and time when the application was created. The date/time format is
	 * per RFC3339 and ISO-8601, and the timezone is UTC. Example:
	 * 2019-04-12T23:20:50.52Z.
	 * 
	 * @return created
	 **/
	@ApiModelProperty(value = "The date and time when the application was created. The date/time format is per RFC3339 and ISO-8601, and the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.")
	public String getCreated() {
		return created;
	}

	/**
	 * Get guid
	 * 
	 * @return guid
	 **/
	@ApiModelProperty(value = "")
	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * Get id
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "")
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Date and time of the last completed scan for this application. The date/time
	 * format is per RFC3339 and ISO-8601, and the timezone is UTC. Example:
	 * 2019-04-12T23:20:50.52Z.
	 * 
	 * @return lastCompletedScanDate
	 **/
	@ApiModelProperty(value = "Date and time of the last completed scan for this application. The date/time format is per RFC3339 and ISO-8601, and the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.")
	public String getLastCompletedScanDate() {
		return lastCompletedScanDate;
	}

	/**
	 * The date and time when the application was modified. The date/time format is
	 * per RFC3339 and ISO-8601, and the timezone is UTC. Example:
	 * 2019-04-12T23:20:50.52Z.
	 * 
	 * @return modified
	 **/
	@ApiModelProperty(value = "The date and time when the application was modified. The date/time format is per RFC3339 and ISO-8601, and the timezone is UTC. Example: 2019-04-12T23:20:50.52Z.")
	public String getModified() {
		return modified;
	}

	/**
	 * Get oid
	 * 
	 * @return oid
	 **/
	@ApiModelProperty(value = "")
	public Integer getOid() {
		return oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * Get organizationId
	 * 
	 * @return organizationId
	 **/
	@ApiModelProperty(value = "")
	public Integer getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	/**
	 * Get profile
	 * 
	 * @return profile
	 **/
	@ApiModelProperty(value = "")
	public ApplicationProfile getProfile() {
		return profile;
	}

	public void setProfile(ApplicationProfile profile) {
		this.profile = profile;
	}

	/**
	 * Unique path to the latest results.
	 * 
	 * @return resultsUrl
	 **/
	@ApiModelProperty(value = "Unique path to the latest results.")
	public String getResultsUrl() {
		return resultsUrl;
	}

	/**
	 * Get scans
	 * 
	 * @return scans
	 **/
	@ApiModelProperty(value = "")
	public List<ApplicationScan> getScans() {
		return scans;
	}

	public void setScans(List<ApplicationScan> scans) {
		this.scans = scans;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Application application = (Application) o;
		return Objects.equals(this.appProfileUrl, application.appProfileUrl)
				&& Objects.equals(this.created, application.created) && Objects.equals(this.guid, application.guid)
				&& Objects.equals(this.id, application.id)
				&& Objects.equals(this.lastCompletedScanDate, application.lastCompletedScanDate)
				&& Objects.equals(this.modified, application.modified) && Objects.equals(this.oid, application.oid)
				&& Objects.equals(this.organizationId, application.organizationId)
				&& Objects.equals(this.profile, application.profile)
				&& Objects.equals(this.resultsUrl, application.resultsUrl)
				&& Objects.equals(this.scans, application.scans);
	}

	@Override
	public int hashCode() {
		return Objects.hash(appProfileUrl, created, guid, id, lastCompletedScanDate, modified, oid, organizationId,
				profile, resultsUrl, scans);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Application {\n");

		sb.append("    appProfileUrl: ").append(toIndentedString(appProfileUrl)).append("\n");
		sb.append("    created: ").append(toIndentedString(created)).append("\n");
		sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    lastCompletedScanDate: ").append(toIndentedString(lastCompletedScanDate)).append("\n");
		sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
		sb.append("    oid: ").append(toIndentedString(oid)).append("\n");
		sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
		sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
		sb.append("    resultsUrl: ").append(toIndentedString(resultsUrl)).append("\n");
		sb.append("    scans: ").append(toIndentedString(scans)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
