/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * AppTeam
 */
public class AppTeam {
	@SerializedName("guid")
	private String guid = null;

	@SerializedName("team_id")
	private Integer teamId = null;

	@SerializedName("team_name")
	private String teamName = null;

	/**
	 * The team ID in the Veracode Identity API.
	 * 
	 * @return guid
	 **/
	@ApiModelProperty(value = "The team ID in the Veracode Identity API.")
	public String getGuid() {
		return guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	/**
	 * The legacy team_id.
	 * 
	 * @return teamId
	 **/
	@ApiModelProperty(value = "The legacy team_id.")
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * Team name.
	 * 
	 * @return teamName
	 **/
	@ApiModelProperty(value = "Team name.")
	public String getTeamName() {
		return teamName;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AppTeam appTeam = (AppTeam) o;
		return Objects.equals(this.guid, appTeam.guid) && Objects.equals(this.teamId, appTeam.teamId)
				&& Objects.equals(this.teamName, appTeam.teamName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(guid, teamId, teamName);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AppTeam {\n");

		sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
		sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
		sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
