/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.io.IOException;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Optional. For a dynamic analysis, indicates whether the scan is DA (Dynamic
 * Analysis), MP (DynamicMP), or DS (DynamicDS).
 */
@JsonAdapter(DynamicScanType.Adapter.class)
public enum DynamicScanType {
	MP("MP"), DS("DS"), DA("DA");

	private String value;

	DynamicScanType(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return String.valueOf(value);
	}

	public static DynamicScanType fromValue(String input) {
		for (DynamicScanType b : DynamicScanType.values()) {
			if (b.value.equals(input)) {
				return b;
			}
		}
		return null;
	}

	public static class Adapter extends TypeAdapter<DynamicScanType> {
		@Override
		public void write(final JsonWriter jsonWriter, final DynamicScanType enumeration) throws IOException {
			jsonWriter.value(String.valueOf(enumeration.getValue()));
		}

		@Override
		public DynamicScanType read(final JsonReader jsonReader) throws IOException {
			Object value = jsonReader.nextString();
			return DynamicScanType.fromValue((String) (value));
		}
	}
}
