/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EmbeddedSandbox
 */
public class EmbeddedSandbox {
	@SerializedName("sandboxes")
	private List<Sandbox> sandboxes = null;

	/**
	 * Get sandboxes
	 * 
	 * @return sandboxes
	 **/
	@ApiModelProperty(value = "")
	public List<Sandbox> getSandboxes() {
		return sandboxes;
	}

	public void setSandboxes(List<Sandbox> sandboxes) {
		this.sandboxes = sandboxes;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmbeddedSandbox embeddedSandbox = (EmbeddedSandbox) o;
		return Objects.equals(this.sandboxes, embeddedSandbox.sandboxes);
	}

	@Override
	public int hashCode() {
		return Objects.hash(sandboxes);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmbeddedSandbox {\n");

		sb.append("    sandboxes: ").append(toIndentedString(sandboxes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
