/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Error
 */

public class Error {
	@SerializedName("message")
	private String message = null;

	@SerializedName("code")
	private String code = null;

	@SerializedName("_links")
	private ErrorLinks _links = null;

	/**
	 * Error message.
	 * 
	 * @return message
	 **/
	public String getMessage() {
		return message;
	}

	/**
	 * Error code.
	 * 
	 * @return code
	 **/
	public String getCode() {
		return code;
	}

	public Error _links(ErrorLinks _links) {
		this._links = _links;
		return this;
	}

	/**
	 * Get _links
	 * 
	 * @return _links
	 **/
	public ErrorLinks getLinks() {
		return _links;
	}

	public void setLinks(ErrorLinks _links) {
		this._links = _links;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Error error = (Error) o;
		return Objects.equals(this.message, error.message) && Objects.equals(this.code, error.code)
				&& Objects.equals(this._links, error._links);
	}

	@Override
	public int hashCode() {
		return Objects.hash(message, code, _links);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Error {\n");

		sb.append("    message: ").append(toIndentedString(message)).append("\n");
		sb.append("    code: ").append(toIndentedString(code)).append("\n");
		sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
