/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * ErrorLinks
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T18:59:41.331Z[GMT]")
public class ErrorLinks {
	@SerializedName("help")
	private Link help = null;

	public ErrorLinks help(Link help) {
		this.help = help;
		return this;
	}

	/**
	 * Get help
	 * 
	 * @return help
	 **/
	public Link getHelp() {
		return help;
	}

	public void setHelp(Link help) {
		this.help = help;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ErrorLinks errorLinks = (ErrorLinks) o;
		return Objects.equals(this.help, errorLinks.help);
	}

	@Override
	public int hashCode() {
		return Objects.hash(help);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ErrorLinks {\n");

		sb.append("    help: ").append(toIndentedString(help)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
