/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Filepaths for the component.
 */
public class FilePathList {
	@SerializedName("filePath")
	private List<FilePath> filePath = null;

	/**
	 * Get filePath
	 * 
	 * @return filePath
	 **/
	public List<FilePath> getFilePath() {
		return filePath;
	}

	public void setFilePath(List<FilePath> filePath) {
		this.filePath = filePath;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FilePathList filePathList = (FilePathList) o;
		return Objects.equals(this.filePath, filePathList.filePath);
	}

	@Override
	public int hashCode() {
		return Objects.hash(filePath);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FilePathList {\n");

		sb.append("    filePath: ").append(toIndentedString(filePath)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
