/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Component license.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T18:59:41.331Z[GMT]")
public class License {
	@SerializedName("name")
	private String name = null;

	@SerializedName("spdx_id")
	private String spdxId = null;

	@SerializedName("license_url")
	private String licenseUrl = null;

	@SerializedName("risk_rating")
	private String riskRating = null;

	public License name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Name of this license.
	 * 
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public License spdxId(String spdxId) {
		this.spdxId = spdxId;
		return this;
	}

	/**
	 * Classification for the license from the Software Package Data Exchange (SPDX)
	 * license list.
	 * 
	 * @return spdxId
	 **/
	public String getSpdxId() {
		return spdxId;
	}

	public void setSpdxId(String spdxId) {
		this.spdxId = spdxId;
	}

	public License licenseUrl(String licenseUrl) {
		this.licenseUrl = licenseUrl;
		return this;
	}

	/**
	 * URL for this license.
	 * 
	 * @return licenseUrl
	 **/
	public String getLicenseUrl() {
		return licenseUrl;
	}

	public void setLicenseUrl(String licenseUrl) {
		this.licenseUrl = licenseUrl;
	}

	public License riskRating(String riskRating) {
		this.riskRating = riskRating;
		return this;
	}

	/**
	 * Risk associated with the use of this license.
	 * 
	 * @return riskRating
	 **/
	public String getRiskRating() {
		return riskRating;
	}

	public void setRiskRating(String riskRating) {
		this.riskRating = riskRating;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		License license = (License) o;
		return Objects.equals(this.name, license.name) && Objects.equals(this.spdxId, license.spdxId)
				&& Objects.equals(this.licenseUrl, license.licenseUrl)
				&& Objects.equals(this.riskRating, license.riskRating);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, spdxId, licenseUrl, riskRating);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class License {\n");

		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    spdxId: ").append(toIndentedString(spdxId)).append("\n");
		sb.append("    licenseUrl: ").append(toIndentedString(licenseUrl)).append("\n");
		sb.append("    riskRating: ").append(toIndentedString(riskRating)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
