/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Link
 */
public class Link {
	@SerializedName("deprecation")
	private String deprecation = null;

	@SerializedName("href")
	private String href = null;

	@SerializedName("hreflang")
	private String hreflang = null;

	@SerializedName("media")
	private String media = null;

	@SerializedName("rel")
	private String rel = null;

	@SerializedName("templated")
	private Boolean templated = null;

	@SerializedName("title")
	private String title = null;

	@SerializedName("type")
	private String type = null;

	/**
	 * Get deprecation
	 * 
	 * @return deprecation
	 **/
	@ApiModelProperty(value = "")
	public String getDeprecation() {
		return deprecation;
	}

	public void setDeprecation(String deprecation) {
		this.deprecation = deprecation;
	}

	/**
	 * Get href
	 * 
	 * @return href
	 **/
	@ApiModelProperty(value = "")
	public String getHref() {
		return href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	/**
	 * Get hreflang
	 * 
	 * @return hreflang
	 **/
	@ApiModelProperty(value = "")
	public String getHreflang() {
		return hreflang;
	}

	public void setHreflang(String hreflang) {
		this.hreflang = hreflang;
	}

	/**
	 * Get media
	 * 
	 * @return media
	 **/
	@ApiModelProperty(value = "")
	public String getMedia() {
		return media;
	}

	public void setMedia(String media) {
		this.media = media;
	}

	/**
	 * Get rel
	 * 
	 * @return rel
	 **/
	@ApiModelProperty(value = "")
	public String getRel() {
		return rel;
	}

	public void setRel(String rel) {
		this.rel = rel;
	}

	/**
	 * Get templated
	 * 
	 * @return templated
	 **/
	@ApiModelProperty(value = "")
	public Boolean isTemplated() {
		return templated;
	}

	public void setTemplated(Boolean templated) {
		this.templated = templated;
	}

	/**
	 * Get title
	 * 
	 * @return title
	 **/
	@ApiModelProperty(value = "")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get type
	 * 
	 * @return type
	 **/
	@ApiModelProperty(value = "")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Link link = (Link) o;
		return Objects.equals(this.deprecation, link.deprecation) && Objects.equals(this.href, link.href)
				&& Objects.equals(this.hreflang, link.hreflang) && Objects.equals(this.media, link.media)
				&& Objects.equals(this.rel, link.rel) && Objects.equals(this.templated, link.templated)
				&& Objects.equals(this.title, link.title) && Objects.equals(this.type, link.type);
	}

	@Override
	public int hashCode() {
		return Objects.hash(deprecation, href, hreflang, media, rel, templated, title, type);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Link {\n");

		sb.append("    deprecation: ").append(toIndentedString(deprecation)).append("\n");
		sb.append("    href: ").append(toIndentedString(href)).append("\n");
		sb.append("    hreflang: ").append(toIndentedString(hreflang)).append("\n");
		sb.append("    media: ").append(toIndentedString(media)).append("\n");
		sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
		sb.append("    templated: ").append(toIndentedString(templated)).append("\n");
		sb.append("    title: ").append(toIndentedString(title)).append("\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
