/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * For Manual Penetration Testing, Veracode applies the confidentiality,
 * integrity, and availability (CIA) triad to generate the final numeric score
 * for the application. The report lists the delivery consultants, if any,
 * followed by scan results.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T18:59:41.331Z[GMT]")
public class ManualAnalysisType {
	@SerializedName("cia_adjustment")
	private Long ciaAdjustment = null;

	@SerializedName("delivery_consultant")
	private List<String> deliveryConsultant = null;

	@SerializedName("modules")
	private Module modules = null;

	@SerializedName("rating")
	private String rating = null;

	@SerializedName("score")
	private Long score = null;

	@SerializedName("next_scan_due")
	private String nextScanDue = null;

	public ManualAnalysisType ciaAdjustment(Long ciaAdjustment) {
		this.ciaAdjustment = ciaAdjustment;
		return this;
	}

	/**
	 * For Manual Penetration Testing, the CIA triad that Veracode applied to the
	 * security score.
	 * 
	 * @return ciaAdjustment
	 **/
	public Long getCiaAdjustment() {
		return ciaAdjustment;
	}

	public void setCiaAdjustment(Long ciaAdjustment) {
		this.ciaAdjustment = ciaAdjustment;
	}

	public ManualAnalysisType deliveryConsultant(List<String> deliveryConsultant) {
		this.deliveryConsultant = deliveryConsultant;
		return this;
	}

	public ManualAnalysisType addDeliveryConsultantItem(String deliveryConsultantItem) {
		if (this.deliveryConsultant == null) {
			this.deliveryConsultant = new ArrayList<String>();
		}
		this.deliveryConsultant.add(deliveryConsultantItem);
		return this;
	}

	/**
	 * For Manual Penetration Testing, the names of the delivery consultants, if
	 * any.
	 * 
	 * @return deliveryConsultant
	 **/
	public List<String> getDeliveryConsultant() {
		return deliveryConsultant;
	}

	public void setDeliveryConsultant(List<String> deliveryConsultant) {
		this.deliveryConsultant = deliveryConsultant;
	}

	public ManualAnalysisType modules(Module modules) {
		this.modules = modules;
		return this;
	}

	/**
	 * Get modules
	 * 
	 * @return modules
	 **/
	public Module getModules() {
		return modules;
	}

	public void setModules(Module modules) {
		this.modules = modules;
	}

	public ManualAnalysisType rating(String rating) {
		this.rating = rating;
		return this;
	}

	/**
	 * Letter grade for the security of this application.
	 * 
	 * @return rating
	 **/
	public String getRating() {
		return rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public ManualAnalysisType score(Long score) {
		this.score = score;
		return this;
	}

	/**
	 * Numeric score for the security of this application.
	 * 
	 * @return score
	 **/
	public Long getScore() {
		return score;
	}

	public void setScore(Long score) {
		this.score = score;
	}

	public ManualAnalysisType nextScanDue(String nextScanDue) {
		this.nextScanDue = nextScanDue;
		return this;
	}

	/**
	 * Date when the active security policy for this application is scheduled to
	 * request the next scan.
	 * 
	 * @return nextScanDue
	 **/
	public String getNextScanDue() {
		return nextScanDue;
	}

	public void setNextScanDue(String nextScanDue) {
		this.nextScanDue = nextScanDue;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ManualAnalysisType manualAnalysisType = (ManualAnalysisType) o;
		return Objects.equals(this.ciaAdjustment, manualAnalysisType.ciaAdjustment)
				&& Objects.equals(this.deliveryConsultant, manualAnalysisType.deliveryConsultant)
				&& Objects.equals(this.modules, manualAnalysisType.modules)
				&& Objects.equals(this.rating, manualAnalysisType.rating)
				&& Objects.equals(this.score, manualAnalysisType.score)
				&& Objects.equals(this.nextScanDue, manualAnalysisType.nextScanDue);
	}

	@Override
	public int hashCode() {
		return Objects.hash(ciaAdjustment, deliveryConsultant, modules, rating, score, nextScanDue);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ManualAnalysisType {\n");

		sb.append("    ciaAdjustment: ").append(toIndentedString(ciaAdjustment)).append("\n");
		sb.append("    deliveryConsultant: ").append(toIndentedString(deliveryConsultant)).append("\n");
		sb.append("    modules: ").append(toIndentedString(modules)).append("\n");
		sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
		sb.append("    score: ").append(toIndentedString(score)).append("\n");
		sb.append("    nextScanDue: ").append(toIndentedString(nextScanDue)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
