/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Module
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T18:59:41.331Z[GMT]")
public class Module {
	@SerializedName("module")
	private List<ModuleType> module = null;

	public Module module(List<ModuleType> module) {
		this.module = module;
		return this;
	}

	public Module addModuleItem(ModuleType moduleItem) {
		if (this.module == null) {
			this.module = new ArrayList<ModuleType>();
		}
		this.module.add(moduleItem);
		return this;
	}

	/**
	 * Module Type array
	 * 
	 * @return module
	 **/
	public List<ModuleType> getModule() {
		return module;
	}

	public void setModule(List<ModuleType> module) {
		this.module = module;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Module module = (Module) o;
		return Objects.equals(this.module, module.module);
	}

	@Override
	public int hashCode() {
		return Objects.hash(module);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Module {\n");

		sb.append("    module: ").append(toIndentedString(module)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
