/*
 * Veracode Applications API Specification
 * Veracode Applications API Documentation  Use one of the following base URLs depending on the region for your account: * https://api.veracode.com/ - Veracode US Region (default) * https://api.veracode.eu/ - Veracode European Region * https://api.veracode.us/ - Veracode US Federal Region
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PagedResourceOfApplication
 */
public class PagedResourceOfApplication extends AbstractPagedResources {
	@SerializedName("_embedded")
	private EmbeddedApplication embedded = null;

	@SerializedName("_links")
	private Link links = null;

	public PagedResourceOfApplication embedded(EmbeddedApplication embedded) {
		this.embedded = embedded;
		return this;
	}

	/**
	 * Get embedded
	 * 
	 * @return embedded
	 **/
	@ApiModelProperty(value = "")
	public EmbeddedApplication getEmbedded() {
		return embedded;
	}

	public void setEmbedded(EmbeddedApplication embedded) {
		this.embedded = embedded;
	}

	public PagedResourceOfApplication links(Link links) {
		this.links = links;
		return this;
	}

	/**
	 * Get links
	 * 
	 * @return links
	 **/
	@ApiModelProperty(value = "")
	public Link getLinks() {
		return links;
	}

	public void setLinks(Link links) {
		this.links = links;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PagedResourceOfApplication pagedResourceOfApplication = (PagedResourceOfApplication) o;
		return Objects.equals(this.embedded, pagedResourceOfApplication.embedded)
				&& Objects.equals(this.links, pagedResourceOfApplication.links)
				&& Objects.equals(getPage(), pagedResourceOfApplication.getPage());
	}

	@Override
	public int hashCode() {
		return Objects.hash(embedded, links, getPage());
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PagedResourceOfApplication {\n");

		sb.append("    embedded: ").append(toIndentedString(embedded)).append("\n");
		sb.append("    links: ").append(toIndentedString(links)).append("\n");
		sb.append("    page: ").append(toIndentedString(getPage())).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
