/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.io.IOException;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * PolicyRuleType enum
 */
@JsonAdapter(PolicyRuleType.Adapter.class)
public enum PolicyRuleType {
	VULNERABILITIES_BY_SEVERITY("DISALLOW_VULNERABILITIES_BY_SEVERITY"), CVSS_SCORE("DISALLOW_CVSS_SCORE"),
	COMPONENT_BLACKLIST("DISALLOW_COMPONENT_BLACKLIST"),
	COMPONENT_BY_LICENSE_RISK("DISALLOW_COMPONENT_BY_LICENSE_RISK");

	private String value;

	PolicyRuleType(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return String.valueOf(value);
	}

	/**
	 * Convert text to PolicyRuleType
	 * 
	 * @param input the text to convert
	 * @return PolicyRuleType or null
	 */
	public static PolicyRuleType fromValue(String input) {
		for (PolicyRuleType b : PolicyRuleType.values()) {
			if (b.value.equals(input)) {
				return b;
			}
		}
		return null;
	}

	/**
	 * Adapter to translate JSON to PolicyRuleType
	 */
	public static class Adapter extends TypeAdapter<PolicyRuleType> {
		@Override
		public void write(final JsonWriter jsonWriter, final PolicyRuleType enumeration) throws IOException {
			jsonWriter.value(String.valueOf(enumeration.getValue()));
		}

		@Override
		public PolicyRuleType read(final JsonReader jsonReader) throws IOException {
			Object value = jsonReader.nextString();
			return PolicyRuleType.fromValue((String) (value));
		}
	}
}
