/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Name of the SCA policy rule.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-02-16T18:59:41.331Z[GMT]")
public class PolicyRule {
	@SerializedName("type")
	private PolicyRuleType type = null;

	@SerializedName("value")
	private String value = null;

	@SerializedName("desc")
	private String desc = null;

	public PolicyRule type(PolicyRuleType type) {
		this.type = type;
		return this;
	}

	/**
	 * Get type
	 * 
	 * @return type
	 **/
	public PolicyRuleType getType() {
		return type;
	}

	public void setType(PolicyRuleType type) {
		this.type = type;
	}

	public PolicyRule value(String value) {
		this.value = value;
		return this;
	}

	/**
	 * SCA policy type.
	 * 
	 * @return value
	 **/
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public PolicyRule desc(String desc) {
		this.desc = desc;
		return this;
	}

	/**
	 * SCA policy description.
	 * 
	 * @return desc
	 **/
	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PolicyRule policyRule = (PolicyRule) o;
		return Objects.equals(this.type, policyRule.type) && Objects.equals(this.value, policyRule.value)
				&& Objects.equals(this.desc, policyRule.desc);
	}

	@Override
	public int hashCode() {
		return Objects.hash(type, value, desc);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PolicyRule {\n");

		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    value: ").append(toIndentedString(value)).append("\n");
		sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
