/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.io.IOException;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Severity enum
 */
@JsonAdapter(SeverityEnum.Adapter.class)
public enum SeverityEnum {
	INFORMATIONAL("Informational"), VERY_LOW("Very Low"), LOW("Low"), MEDIUM("Medium"), HIGH("High"),
	VERY_HIGH("Very High");

	private String value;

	SeverityEnum(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

	@Override
	public String toString() {
		return String.valueOf(value);
	}

	public static SeverityEnum fromValue(String input) {
		for (SeverityEnum b : SeverityEnum.values()) {
			if (b.value.equals(input)) {
				return b;
			}
		}
		return null;
	}

	public static class Adapter extends TypeAdapter<SeverityEnum> {
		@Override
		public void write(final JsonWriter jsonWriter, final SeverityEnum enumeration) throws IOException {
			jsonWriter.value(String.valueOf(enumeration.getValue()));
		}

		@Override
		public SeverityEnum read(final JsonReader jsonReader) throws IOException {
			Object value = jsonReader.nextString();
			return SeverityEnum.fromValue((String) (value));
		}
	}
}
