/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Information about the Veracode Levels for the severity of a finding. The
 * range is 0 through 5, where 0 is informational and 5 is the most severe.
 */
public class SeverityType {
	@SerializedName("category")
	private List<CategoryType> category = null;

	@SerializedName("level")
	private Integer level = null;

	public SeverityType category(List<CategoryType> category) {
		this.category = category;
		return this;
	}

	public SeverityType addCategoryItem(CategoryType categoryItem) {
		if (this.category == null) {
			this.category = new ArrayList<CategoryType>();
		}
		this.category.add(categoryItem);
		return this;
	}

	/**
	 * Category of findings with one per category for which there is at least one
	 * finding.
	 * 
	 * @return category
	 **/
	public List<CategoryType> getCategory() {
		return category;
	}

	public void setCategory(List<CategoryType> category) {
		this.category = category;
	}

	public SeverityType level(Integer level) {
		this.level = level;
		return this;
	}

	/**
	 * Veracode Level for the severity of the finding. The value range is 0 to 5,
	 * with 5 being the highest severity.
	 * 
	 * @return level
	 **/
	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SeverityType severityType = (SeverityType) o;
		return Objects.equals(this.category, severityType.category) && Objects.equals(this.level, severityType.level);
	}

	@Override
	public int hashCode() {
		return Objects.hash(category, level);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SeverityType {\n");

		sb.append("    category: ").append(toIndentedString(category)).append("\n");
		sb.append("    level: ").append(toIndentedString(level)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
