/*
 * Veracode Summary Report API
 * Veracode Summary Report API Documentation
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.tracelink.prodsec.lib.veracode.api.rest.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

/**
 * Information about findings discovered during Software Composition Analysis
 * (SCA).
 */
public class SoftwareCompositionAnalysis {
	@SerializedName("vulnerable_components")
	private VulnerableComponentList vulnerableComponents = null;

	@SerializedName("third_party_components")
	private Long thirdPartyComponents = null;

	@SerializedName("violate_policy")
	private Boolean violatePolicy = null;

	@SerializedName("components_violated_policy")
	private Long componentsViolatedPolicy = null;

	@SerializedName("blacklisted_components")
	private Long blacklistedComponents = null;

	@SerializedName("sca_service_available")
	private Boolean scaServiceAvailable = null;

	public SoftwareCompositionAnalysis vulnerableComponents(VulnerableComponentList vulnerableComponents) {
		this.vulnerableComponents = vulnerableComponents;
		return this;
	}

	/**
	 * Get vulnerableComponents
	 * 
	 * @return vulnerableComponents
	 **/
	public VulnerableComponentList getVulnerableComponents() {
		return vulnerableComponents;
	}

	public void setVulnerableComponents(VulnerableComponentList vulnerableComponents) {
		this.vulnerableComponents = vulnerableComponents;
	}

	public SoftwareCompositionAnalysis thirdPartyComponents(Long thirdPartyComponents) {
		this.thirdPartyComponents = thirdPartyComponents;
		return this;
	}

	/**
	 * Number of vulnerable third party components.
	 * 
	 * @return thirdPartyComponents
	 **/
	public Long getThirdPartyComponents() {
		return thirdPartyComponents;
	}

	public void setThirdPartyComponents(Long thirdPartyComponents) {
		this.thirdPartyComponents = thirdPartyComponents;
	}

	public SoftwareCompositionAnalysis violatePolicy(Boolean violatePolicy) {
		this.violatePolicy = violatePolicy;
		return this;
	}

	/**
	 * Whether the component violates the security policy.
	 * 
	 * @return violatePolicy
	 **/
	public Boolean isViolatePolicy() {
		return violatePolicy;
	}

	public void setViolatePolicy(Boolean violatePolicy) {
		this.violatePolicy = violatePolicy;
	}

	public SoftwareCompositionAnalysis componentsViolatedPolicy(Long componentsViolatedPolicy) {
		this.componentsViolatedPolicy = componentsViolatedPolicy;
		return this;
	}

	/**
	 * Number of components that violate the SCA policy.
	 * 
	 * @return componentsViolatedPolicy
	 **/
	public Long getComponentsViolatedPolicy() {
		return componentsViolatedPolicy;
	}

	public void setComponentsViolatedPolicy(Long componentsViolatedPolicy) {
		this.componentsViolatedPolicy = componentsViolatedPolicy;
	}

	public SoftwareCompositionAnalysis blacklistedComponents(Long blacklistedComponents) {
		this.blacklistedComponents = blacklistedComponents;
		return this;
	}

	/**
	 * Number of blacklisted components.
	 * 
	 * @return blacklistedComponents
	 **/
	public Long getBlacklistedComponents() {
		return blacklistedComponents;
	}

	public void setBlacklistedComponents(Long blacklistedComponents) {
		this.blacklistedComponents = blacklistedComponents;
	}

	public SoftwareCompositionAnalysis scaServiceAvailable(Boolean scaServiceAvailable) {
		this.scaServiceAvailable = scaServiceAvailable;
		return this;
	}

	/**
	 * True if the SCA service is available, else set to false.
	 * 
	 * @return scaServiceAvailable
	 **/
	public Boolean isScaServiceAvailable() {
		return scaServiceAvailable;
	}

	public void setScaServiceAvailable(Boolean scaServiceAvailable) {
		this.scaServiceAvailable = scaServiceAvailable;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SoftwareCompositionAnalysis softwareCompositionAnalysis = (SoftwareCompositionAnalysis) o;
		return Objects.equals(this.vulnerableComponents, softwareCompositionAnalysis.vulnerableComponents)
				&& Objects.equals(this.thirdPartyComponents, softwareCompositionAnalysis.thirdPartyComponents)
				&& Objects.equals(this.violatePolicy, softwareCompositionAnalysis.violatePolicy)
				&& Objects.equals(this.componentsViolatedPolicy, softwareCompositionAnalysis.componentsViolatedPolicy)
				&& Objects.equals(this.blacklistedComponents, softwareCompositionAnalysis.blacklistedComponents)
				&& Objects.equals(this.scaServiceAvailable, softwareCompositionAnalysis.scaServiceAvailable);
	}

	@Override
	public int hashCode() {
		return Objects.hash(vulnerableComponents, thirdPartyComponents, violatePolicy, componentsViolatedPolicy,
				blacklistedComponents, scaServiceAvailable);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SoftwareCompositionAnalysis {\n");

		sb.append("    vulnerableComponents: ").append(toIndentedString(vulnerableComponents)).append("\n");
		sb.append("    thirdPartyComponents: ").append(toIndentedString(thirdPartyComponents)).append("\n");
		sb.append("    violatePolicy: ").append(toIndentedString(violatePolicy)).append("\n");
		sb.append("    componentsViolatedPolicy: ").append(toIndentedString(componentsViolatedPolicy)).append("\n");
		sb.append("    blacklistedComponents: ").append(toIndentedString(blacklistedComponents)).append("\n");
		sb.append("    scaServiceAvailable: ").append(toIndentedString(scaServiceAvailable)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
