//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:26 PM EDT 
//


package com.tracelink.prodsec.lib.veracode.api.xml.data.buildlist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The build type element contains the key elements and attributes
 * that reflect the data we store for a build.
 * <p>
 * * policy_updated_date represents the last time an action
 * occurred which might have affected policy compliance.
 *
 *
 * <p>Java class for BuildType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BuildType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="build_id" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="version" type="{https://analysiscenter.veracode.com/schema/2.0/buildlist}LongRequiredTextType" /&gt;
 *       &lt;attribute name="policy_updated_date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dynamic_scan_type" type="{https://analysiscenter.veracode.com/schema/2.0/buildlist}DynamicScanType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildType", namespace = "https://analysiscenter.veracode.com/schema/2.0/buildlist")
public class BuildType {

	@XmlAttribute(name = "build_id")
	private Long buildId;
	@XmlAttribute(name = "version")
	private String version;
	@XmlAttribute(name = "policy_updated_date")
	private String policyUpdatedDate;
	@XmlAttribute(name = "dynamic_scan_type")
	private DynamicScanType dynamicScanType;

	/**
	 * Gets the value of the buildId property.
	 *
	 * @return possible object is
	 * {@link Long }
	 */
	public Long getBuildId() {
		return buildId;
	}

	/**
	 * Sets the value of the buildId property.
	 *
	 * @param value allowed object is
	 *              {@link Long }
	 */
	public void setBuildId(Long value) {
		this.buildId = value;
	}

	/**
	 * Gets the value of the version property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the policyUpdatedDate property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getPolicyUpdatedDate() {
		return policyUpdatedDate;
	}

	/**
	 * Sets the value of the policyUpdatedDate property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setPolicyUpdatedDate(String value) {
		this.policyUpdatedDate = value;
	}

	/**
	 * Gets the value of the dynamicScanType property.
	 *
	 * @return possible object is
	 * {@link DynamicScanType }
	 */
	public DynamicScanType getDynamicScanType() {
		return dynamicScanType;
	}

	/**
	 * Sets the value of the dynamicScanType property.
	 *
	 * @param value allowed object is
	 *              {@link DynamicScanType }
	 */
	public void setDynamicScanType(DynamicScanType value) {
		this.dynamicScanType = value;
	}

}
