//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.lib.veracode.xml.api.data.detailedreport;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * For each CWE entry, there are the following attributes:
 * * cweId:  The CWE ID for the flaw type.
 * * cwename:  The name of the CWE flaw type.
 * * owasp:  The OWASP ID for the CWE flaw type if it applies.
 * * owasp2013:  The Legacy OWASP 2013 ID for the CWE flaw type if it applies.
 * * sans:  The SANS ID for the CWE flaw type if it applies.
 * * certc:  The CERTC ID for the CWE flaw type if it applies.
 * * certcpp:  The CERTCPP ID for the CWE flaw type if it applies.
 * * certjava:  The CERTJAVA ID for the CWE flaw type if it applies.
 * * owaspmobile:  The OWASP Mobile 2016 ID for the CWE flaw type if it applies.
 * <p>
 * This element has these child elements:
 * * staticflaws:  If flaws of this type are found through static analysis,
 * those flaws are grouped under this element.
 * * dynamicflaws:  If flaws of this type are found through dynamic analysis,
 * those flaws are grouped under this element.
 * * pcirelated:  Whether the flaw is PCI related.  (This will be specified in a
 * future release of the platform.)
 *
 *
 * <p>Java class for CweType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CweType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="text" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="staticflaws" type="{https://www.veracode.com/schema/reports/export/1.0}FlawListType" minOccurs="0"/&gt;
 *         &lt;element name="dynamicflaws" type="{https://www.veracode.com/schema/reports/export/1.0}FlawListType" minOccurs="0"/&gt;
 *         &lt;element name="manualflaws" type="{https://www.veracode.com/schema/reports/export/1.0}FlawListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="cweid" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="cwename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="pcirelated" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="owasp" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="owasp2013" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="sans" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="certc" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="certcpp" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="certjava" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *       &lt;attribute name="owaspmobile" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CweType", namespace = "https://www.veracode.com/schema/reports/export/1.0", propOrder = {"description", "staticflaws", "dynamicflaws", "manualflaws"})
public class CweType {

	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0", required = true)
	private CweType.Description description;
	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private FlawListType staticflaws;
	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private FlawListType dynamicflaws;
	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
	private FlawListType manualflaws;
	@XmlAttribute(name = "cweid", required = true)
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger cweid;
	@XmlAttribute(name = "cwename", required = true)
	private String cwename;
	@XmlAttribute(name = "pcirelated")
	private Boolean pcirelated;
	@XmlAttribute(name = "owasp")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger owasp;
	@XmlAttribute(name = "owasp2013")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger owasp2013;
	@XmlAttribute(name = "sans")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger sans;
	@XmlAttribute(name = "certc")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger certc;
	@XmlAttribute(name = "certcpp")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger certcpp;
	@XmlAttribute(name = "certjava")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger certjava;
	@XmlAttribute(name = "owaspmobile")
	@XmlSchemaType(name = "positiveInteger")
	private BigInteger owaspmobile;

	/**
	 * Gets the value of the description property.
	 *
	 * @return possible object is
	 * {@link CweType.Description }
	 */
	public CweType.Description getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is
	 *              {@link CweType.Description }
	 */
	public void setDescription(CweType.Description value) {
		this.description = value;
	}

	/**
	 * Gets the value of the staticflaws property.
	 *
	 * @return possible object is
	 * {@link FlawListType }
	 */
	public FlawListType getStaticflaws() {
		return staticflaws;
	}

	/**
	 * Sets the value of the staticflaws property.
	 *
	 * @param value allowed object is
	 *              {@link FlawListType }
	 */
	public void setStaticflaws(FlawListType value) {
		this.staticflaws = value;
	}

	/**
	 * Gets the value of the dynamicflaws property.
	 *
	 * @return possible object is
	 * {@link FlawListType }
	 */
	public FlawListType getDynamicflaws() {
		return dynamicflaws;
	}

	/**
	 * Sets the value of the dynamicflaws property.
	 *
	 * @param value allowed object is
	 *              {@link FlawListType }
	 */
	public void setDynamicflaws(FlawListType value) {
		this.dynamicflaws = value;
	}

	/**
	 * Gets the value of the manualflaws property.
	 *
	 * @return possible object is
	 * {@link FlawListType }
	 */
	public FlawListType getManualflaws() {
		return manualflaws;
	}

	/**
	 * Sets the value of the manualflaws property.
	 *
	 * @param value allowed object is
	 *              {@link FlawListType }
	 */
	public void setManualflaws(FlawListType value) {
		this.manualflaws = value;
	}

	/**
	 * Gets the value of the cweid property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getCweid() {
		return cweid;
	}

	/**
	 * Sets the value of the cweid property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setCweid(BigInteger value) {
		this.cweid = value;
	}

	/**
	 * Gets the value of the cwename property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getCwename() {
		return cwename;
	}

	/**
	 * Sets the value of the cwename property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setCwename(String value) {
		this.cwename = value;
	}

	/**
	 * Gets the value of the pcirelated property.
	 *
	 * @return possible object is
	 * {@link Boolean }
	 */
	public Boolean isPcirelated() {
		return pcirelated;
	}

	/**
	 * Sets the value of the pcirelated property.
	 *
	 * @param value allowed object is
	 *              {@link Boolean }
	 */
	public void setPcirelated(Boolean value) {
		this.pcirelated = value;
	}

	/**
	 * Gets the value of the owasp property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getOwasp() {
		return owasp;
	}

	/**
	 * Sets the value of the owasp property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setOwasp(BigInteger value) {
		this.owasp = value;
	}

	/**
	 * Gets the value of the owasp2013 property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getOwasp2013() {
		return owasp2013;
	}

	/**
	 * Sets the value of the owasp2013 property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setOwasp2013(BigInteger value) {
		this.owasp2013 = value;
	}

	/**
	 * Gets the value of the sans property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getSans() {
		return sans;
	}

	/**
	 * Sets the value of the sans property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setSans(BigInteger value) {
		this.sans = value;
	}

	/**
	 * Gets the value of the certc property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getCertc() {
		return certc;
	}

	/**
	 * Sets the value of the certc property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setCertc(BigInteger value) {
		this.certc = value;
	}

	/**
	 * Gets the value of the certcpp property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getCertcpp() {
		return certcpp;
	}

	/**
	 * Sets the value of the certcpp property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setCertcpp(BigInteger value) {
		this.certcpp = value;
	}

	/**
	 * Gets the value of the certjava property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getCertjava() {
		return certjava;
	}

	/**
	 * Sets the value of the certjava property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setCertjava(BigInteger value) {
		this.certjava = value;
	}

	/**
	 * Gets the value of the owaspmobile property.
	 *
	 * @return possible object is
	 * {@link BigInteger }
	 */
	public BigInteger getOwaspmobile() {
		return owaspmobile;
	}

	/**
	 * Sets the value of the owaspmobile property.
	 *
	 * @param value allowed object is
	 *              {@link BigInteger }
	 */
	public void setOwaspmobile(BigInteger value) {
		this.owaspmobile = value;
	}


	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name="text" maxOccurs="unbounded" minOccurs="0"&gt;
	 *           &lt;complexType&gt;
	 *             &lt;complexContent&gt;
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
	 *                 &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
	 *               &lt;/restriction&gt;
	 *             &lt;/complexContent&gt;
	 *           &lt;/complexType&gt;
	 *         &lt;/element&gt;
	 *       &lt;/sequence&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {"text"})
	public static class Description {

		@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0")
		private List<CweType.Description.Text> text;

		/**
		 * Gets the value of the text property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the text property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getText().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link CweType.Description.Text }
		 *
		 * @return value of the text property, or an empty list if the text property is null
		 */
		public List<CweType.Description.Text> getText() {
			if (text == null) {
				text = new ArrayList<>();
			}
			return this.text;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this
		 * class.
		 *
		 * <pre>
		 * &lt;complexType&gt;
		 *   &lt;complexContent&gt;
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
		 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
		 *     &lt;/restriction&gt;
		 *   &lt;/complexContent&gt;
		 * &lt;/complexType&gt;
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Text {

			@XmlAttribute(name = "text", required = true)
			private String text;

			/**
			 * Gets the value of the text property.
			 *
			 * @return possible object is
			 * {@link String }
			 */
			public String getText() {
				return text;
			}

			/**
			 * Sets the value of the text property.
			 *
			 * @param value allowed object is
			 *              {@link String }
			 */
			public void setText(String value) {
				this.text = value;
			}

		}

	}

}
