//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.lib.veracode.xml.api.data.detailedreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The element describes a screen shot for a flaw. There is a
 * format element to describe the file type, and the code
 * element will contain a base64 encoding of the actual binary
 * file.
 *
 *
 * <p>Java class for ScreenshotType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ScreenshotType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="format" use="required" type="{https://www.veracode.com/schema/reports/export/1.0}ScreenshotFormatType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScreenshotType", namespace = "https://www.veracode.com/schema/reports/export/1.0", propOrder = {
		"data"
})
public class ScreenshotType {

	@XmlElement(namespace = "https://www.veracode.com/schema/reports/export/1.0", required = true)
	private byte[] data;
	@XmlAttribute(name = "format", required = true)
	private ScreenshotFormatType format;

	/**
	 * Gets the value of the data property.
	 *
	 * @return possible object is
	 * byte[]
	 */
	public byte[] getData() {
		return data;
	}

	/**
	 * Sets the value of the data property.
	 *
	 * @param value allowed object is
	 *              byte[]
	 */
	public void setData(byte[] value) {
		this.data = value;
	}

	/**
	 * Gets the value of the format property.
	 *
	 * @return possible object is
	 * {@link ScreenshotFormatType }
	 */
	public ScreenshotFormatType getFormat() {
		return format;
	}

	/**
	 * Sets the value of the format property.
	 *
	 * @param value allowed object is
	 *              {@link ScreenshotFormatType }
	 */
	public void setFormat(ScreenshotFormatType value) {
		this.format = value;
	}

}
