//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:30:35 PM EDT 
//


package com.tracelink.prodsec.lib.veracode.xml.api.data.detailedreport;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScreenshotFormatType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;simpleType name="ScreenshotFormatType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GIF"/&gt;
 *     &lt;enumeration value="JPG"/&gt;
 *     &lt;enumeration value="PNG"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "ScreenshotFormatType", namespace = "https://www.veracode.com/schema/reports/export/1.0")
@XmlEnum
public enum ScreenshotFormatType {

	GIF,
	JPG,
	PNG;

	/**
	 * Gets the value of this screenshot format type
	 *
	 * @return the screenshot format type
	 */
	public String value() {
		return name();
	}

	/**
	 * Gets the {@link ScreenshotFormatType} for the given value.
	 *
	 * @param v the value to get the screenshot format type for
	 * @return the screenshot format type
	 */
	public static ScreenshotFormatType fromValue(String v) {
		return valueOf(v);
	}

}
