server:
  port: 8081

spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}

  thymeleaf:
    cache: true
  flyway:
    locations: classpath:db/core

  #synapse:
  #  encryption:
  #    type: environment
  #    environment:
  #      currentKeyStorePath: ${CURRENT_KEYSTORE}
  #      currentKeyStorePassword: ${CURRENT_KEYSTORE_PASSWORD}
