server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/synapse #${JDBC_URL}
    username: appsecmaster #${JDBC_USERNAME}
    password: synapse #${JDBC_PASSWORD}
  thymeleaf:
    cache: true
  flyway:
    locations: classpath:db/core

  #synapse:
  #  encryption:
  #    type: environment
  #    environment:
  #      currentKeyStorePath: ${CURRENT_KEYSTORE}
  #      currentKeyStorePassword: ${CURRENT_KEYSTORE_PASSWORD}
